applications/ebos/eclgridmanager.hh
applications/ebos/eclproblem.hh
applications/ebos/ecltransmissibility.hh
applications/ebos/eclwellmanager.hh
cmake/Modules/FindMETIS.cmake
cmake/Modules/FindZOLTAN.cmake
cmake/Modules/Finddune-alugrid.cmake
cmake/Scripts/configure

This patch makes the ebos simulator compile with ALUGrid (and by that assure that the code still follows the DUNE grid interface). 
For that reasons the identification to the Cartesian cell id has been moved to the grid manager. 
Some minor other fixes have been made to make the code compile. 
Also, I added the FindZOLTAN.cmake check but for some reasons it is not working correctly yet. 
The switch between CpGrid and ALUGrid needs to be put into the ewoms way by @andlaus.

EclSimulator: make compile with dune-alugrid

---

ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaselinearizer.hh
ewoms/models/common/multiphasebasemodel.hh
ewoms/models/pvs/pvsmodel.hh
ewoms/models/stokes/stokesmodel.hh

The reason is that entities will be copied. To be on the save side, we just dereference the iterator once. 
This PR fixed some of the occurrences, but probably not all of them.

In dune 2.4 and later it will be necessary to avoid iterator dereferencing.

---

CMakeLists.txt
bin/runtest.sh

The most important issue was that PR#20 removed the possibility to use
a test driver script. In eWoms, this script is responsible for
(fuzzily) comparing the results of the test runs with reference
solutions, to test the simulators in parallel and compare the results,
and to make sure that the --help command continues to work as
intended.
the approach taken to bring this functionality back is to specify the
test driver script and its parameters using the new macro
'opm_set_test_driver(${DRIVER_COMMAND} ${DRIVER_DEFAULT_ARGUMENTS})'
before the first call to 'opm_add_test'. If no test driver is
specified, the binary is run 'naked', so nothing should change in this
case.
this patch requires the changes for opm-cmake (OPM/opm-cmake#14) to be merged first.

fix the regressions caused by PR#20

---

applications/ebos/eclequilinitializer.hh

The constructor in BlackoilPropertiesFromDeck has changed and this PR fixes this.

EclEquilInitializer: adjust to BlackoilPropertiesFromDeck changes from opm-core.

---

redhat/ewoms.spec

- el5 removed
- el7 added
additionally i had to disable the documentation on el6 as it crashes doxygen. i don't feel like hunting down a bug in an 8 year old doxygen version.

update redhat packaging

---

CMakeLists.txt
applications/art2dgf.cc

the utility is now more verbose (it actually prints what it does or
does not do), the test converts the example ART file shipped with
eWoms, and finally the art2dgf utility is now not considered a "unit
test" anymore (instead, it is an application).

improve the art2dgf utility and unit test

---

ewoms/io/vtkblackoilmodule.hh

this basically makes everything work again once OPM/opm-material#94 has been merged.
in addition, more quantities can now be written by the blackoil VTK module.

blackoil VTK module: make it more comprehesive and adapt to the mass fraction to surface volume API change in opm-material

---

applications/ebos/eclproblem.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaseelementcontext.hh
ewoms/disc/common/fvbaselocalresidual.hh
ewoms/disc/common/fvbaseproperties.hh

this is a bit hacky because it assumes that an Euler time discretization is used and that the solution for the time indices 0 and 1 are identical at the beginning of a time step. Nevertheless, it saves us from updating the intensive variables for solutions other than the one of the current iteration.
on my machine, this accelerates the linearization with ebos by about 30% for SPE9 (6.4 instead of 8.7 seconds, but the linearization still takes up the largest time chunk with about 50% of the total time spend).

Implement storage cache

---

applications/ebos/eclequilinitializer.hh
applications/ebos/ecloutputblackoilmodule.hh
applications/ebos/eclproblem.hh
ewoms/io/vtkblackoilmodule.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
tests/problems/reservoirproblem.hh

these are the changes required to keep ewoms compileable after OPM/opm-material#102 has been merged.

adapt to the recent blackoil API changes of opm-material

---

ewoms/disc/common/fvbasediscretization.hh

This PR fixed the double free corruption at the end of an adaptive run. The problem was wrong appearance of variables (solution and restrictProlong).

Fvbasediscretization: fix double free coruption

---

ewoms/common/start.hh

Start: Dune::Exception is not derived from std::exception

---

applications/ebos/ecloutputblackoilmodule.hh
ewoms/io/vtkblackoilmodule.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh

the change for the inverse formation volume factors (instead of the
FVFs) is needed to keep the build happy, using the new
getRv_()/getRs_() infrastructure might slightly improve
performance. (the emphasis is *slightly* because it only changes
something if BlackOilFluidState is used for initialization and
initialization is not time critical in the first place.)
the changes of this PR are required to keep the build happy after OPM/opm-material#114 has been merged.

adapt to the recent API changes in opm-material

---

CMakeLists.txt
INSTALL
applications/ebos/collecttoiorank.hh
applications/ebos/eclproblem.hh
applications/ebos/eclwriter.hh
applications/ebos/ertwrappers.hh
dune.module

This updates code to refer to opm-grid instead of dune-cornerpoint.
Requires OPM/opm-common#104.

Renaming dune-cornerpoint -> opm-grid.

---

applications/ebos/eclwellmanager.hh
applications/ebos/ertwrappers.hh

the WellConstPtr typedef is gone

fixed: restore build of ebos after opm-parser changes

---

applications/ebos/ecloutputblackoilmodule.hh
applications/ebos/eclproblem.hh
ewoms/io/vtkblackoilmodule.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilnewtonmethod.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh

this implements support for the VAPPARS keyword in ebos. it depends on OPM/opm-material#154.

ebos: implement support for the VAPPARS keyword

---

applications/ebos/eclthresholdpressure.hh
applications/ebos/ecltransmissibility.hh

getTransMult and getSimulationConfig are no longer returned as shared_ptr from parser, but as references.  Updated use in ewoms.
Downstream of OPM/opm-parser#890.

Reflect changes in parser api, removed shared_ptr

---

.travis.yml
travis/build-and-test-ewoms.sh
travis/build-ewoms.sh

this patch is based on the travis files from opm-material, so it may be that they work. (I've no experience with travis yet, nor do I know a way to test this besides the live system, so bear with me.)
this will not break anything outside travis, so I'll be self-merging immediately.

add the control files for the travis CI system

---

applications/ebos/ertwrappers.hh

Wanted to rename some #define symbols in ert. That was initially done a bit too fast: https://github.com/Ensembles/ert/pull/1214 - then partially reverted here: https://github.com/Ensembles/ert/pull/1215
Anyway - this PR is a step towards completely removing the `_ITEM` form.

Renamed ert constants '_ITEM' -> '_INDEX'.

---

applications/ebos/eclproblem.hh
applications/ebos/ecltransmissibility.hh

this adds support for geologic events during the simulation (e.g. pore volume changes of changing faults in the SCHEDULE section). The code currently has the same limitations as the one for flow in opm-simulators: these geologic events may only change the porosity of some cells or the values of the transmissibility, i.e., changes to the grid topology are not possible.

ebos: add support for geology changes during the simulation

---

applications/ebos/eclfluxmodule.hh
applications/ebos/eclproblem.hh
ewoms/disc/ecfv/ecfvstencil.hh

This replaces the grid.cellCenterDepth method with the correct DUNE interface usage for the same computation.

Use correct cellcenterdepth

---

ewoms/disc/common/fvbaseelementcontext.hh
ewoms/disc/common/fvbaselinearizer.hh
ewoms/disc/ecfv/ecfvstencil.hh
ewoms/disc/vcfv/vcfvstencil.hh
tests/problems/richardslensproblem.hh
tests/test_quadrature.cc

This PR makes the mapper inside the Stencil class a reference, to avoid re-computation of offsets etc.

[feature] Make mapper inside stencil a reference to avoid re-computation.

---

ewoms/disc/common/fvbaseelementcontext.hh

With clang/libc++ this gives a static assertation failure.

Fix mismatch between vector and allocator.

---

ewoms/linear/paralleliterativebackend.hh
tests/problems/co2injectionproblem.hh

the issue only bites if the tests are compiled in debug mode, so it
has only been discovered now.

fix a signedness issue when retrieving parameters

---

ewoms/version.hh

this did not bite earlier because the standard eWoms tests only
include this file once. (it will run into trouble if it is included
multiple times.)

add missing header guards to version.hh

---

ewoms/common/timer.hh

this makes a few annoyances due to buggy target systems go away, but
on the flipside, the CPU time measurements get a few orders of
magnitude less precise on Linux systems. (the measurements of real
time should stay unaffected, though.)
medium-term this class should be replaced by Dune::Timer in my
opinion, but that would be a more invasive endeavor.

Timer: switch to std::chrono

---

ebos/eclproblem.hh

this allows external code (i.e., flow_ebos) to reuse it.

ebos: export the ECL material law manager

---

CMakeLists.txt

condition must be explicit now, since HAVE_OPM_GRID no longer implies HAVE_OPM_CORE.

fixed: only build ebos if opm-core was found

---

dune.module

opm-core is required for ebos and since it is now no longer an implicit dependency of opm-grid, we need to add it here. (more precisely: ebos uses it for the hydrostatic-conditions-as-initial-solution part.)  without this, dunecontrol does not include opm-core.

dune.module: add a opm-core suggestion

---

ewoms/linear/domesticoverlapfrombcrsmatrix.hh
ewoms/linear/foreignoverlapfrombcrsmatrix.hh
ewoms/linear/overlappingbcrsmatrix.hh
ewoms/linear/overlappingblockvector.hh
ewoms/linear/parallelamgbackend.hh
ewoms/linear/paralleliterativebackend.hh
ewoms/linear/weightedresidreductioncriterion.hh
tests/lens_immiscible_ecfv.cc

The floating point type which ought to be used internally by the iterative linear solvers can now be specified via the "LinearSolverScalar" property. It defaults to "Scalar", so this patch does not change the default behaviour.
The most common case of this is probably to use single precision floating point scalars for the linear solver and to do the linearization using double precision. For the lens_immiscible_ecfv test problem with two grid refinements, the performance improvements seem to be considerable: On my machine the linear solver speedup is almost 50%. On the flip-side, there are precission problems, so the tolerance of the Newton-Raphson solver must be relaxed when using single-precision for the linear solver.
The exact command which I used for that measurement is:
``` …
```

make it possible to specify a separate floating-point type of the linear solver

---

ebos/eclbasegridmanager.hh
ebos/eclcpgridmanager.hh
ebos/ecldeckunits.hh
ebos/eclequilinitializer.hh
ebos/eclproblem.hh
ebos/eclsummarywriter.hh
ebos/eclthresholdpressure.hh
ebos/ecltransmissibility.hh
ebos/eclwellmanager.hh
ebos/eclwriter.hh
ebos/ertwrappers.hh
ewoms/io/basegridmanager.hh

this makes creating the grid a bit slower because the
transmissibilities need to be calculated twice: once for the
sequential grid and once for the distributed one. while corresponds to
the way `flow_legacy` does the load balancing and it should allow
better results, this does not seem to be the case for the Norne deck
if ZOLTAN is not available:
After loadbalancing process 3 has 4413 cells.
After loadbalancing process 2 has 12390 cells.
After loadbalancing process 0 has 13629 cells.
After loadbalancing process 1 has 21253 cells.
i.e., process 1 is responsible for about 4 times the number of cells
as process 3.
Note that this PR includes #102 (which should go in before).

Transmissibility edge weights

---

ewoms/linear/parallelamgbackend.hh
ewoms/linear/paralleliterativebackend.hh

this changes the default value for the maximum number of linear iterations of the non-AMG solvers from 250 to 1000 and relaxes the absolute tolerance for the linear solvers.
This improves the performance of some tests while the chances that it causes regressions elsewhere are pretty slim IMO.

Linear solver tuning

---

ewoms/common/start.hh

sometimes incorrect user defined locale settings caused trouble, so
let's reset them to the defaults before we do anything real. (also,
mixing locales in the output looks quite weird IMO:
e.g. German-formatted numbers and English text do not go too well
together.)

start(): reset the locale on startup

---

ebos/eclproblem.hh

this regression was found by @totto82. it was introduced when the explicit prefetching feature was added. Since it only affected decks with geology changes in the SCHEDULE section (a.k.a. Model 2), analysing this issue must have been a *huge* nightmare, so I owe @totto82 at least one beer.

ebos: update the PffGridVector for transmissibility after geologic events

---

ebos/eclproblem.hh
ebos/eclsummarywriter.hh

the issue addressed by the second patch fixes a segfault in ebos for decks with an empty SUMMARY section...

two minor bug fixes

---

ewoms/nonlinear/newtonmethod.hh

the "update..." message of the newton loop was not cleared and if the
end-of-iteration message was shorter than the update message, it was
suffixed by a few junk characters.

fix minor output bug

---

ewoms/common/simulator.hh
ewoms/common/timer.hh
ewoms/common/timerguard.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/nonlinear/newtonmethod.hh

because it seems to be the spirit of the season, here are some timer related improvements: With this, `Ewoms::Timer` uses basically the same semantics as `Dune::Timer`. In contrast to `Dune::Timer`, `Ewoms::Timer` objects can be summed up, measure CPU time and support determining the total CPU time of the whole MPI parallel simulation.
another neat (IMO) addition of this PR is `Ewoms::TimerGuard` which ensures that a timer is stopped once the `TimerGuard` object goes out of scope. This is particularly useful if a function is terminated by an exception thrown by a called function.

Improve timer

---

ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaseproblem.hh

the non-linear solver is (and always has been) an internal implementation detail of the model, so passing an object other than the internal Newton Raphson solver would not have worked anyway.

do not pass a reference to the non-linear solver to Model::update()

---

ewoms/disc/common/fvbaselinearizer.hh
ewoms/linear/parallelbicgstabbackend.hh
ewoms/models/blackoil/blackoilnewtonmethod.hh
ewoms/models/pvs/pvsmodel.hh

this affects MPI-parallel runs of models that use primary variable switching, i.e. the PVS and the blackoil models. this was not noticed earlier because exceptions raised in this part of the code are quite rare. (but sometimes sh** hits the fan!)

properly deal with exceptions thrown while switching the primary variables

---

ewoms/nonlinear/newtonmethod.hh

the purpose of this is to print the error for the last iteration of a timestep to the terminal.

newton: also call the endIteration_() callback if we do not need to solve the linearized system of equations

---

ewoms/common/genericguard.hh
ewoms/linear/bicgstabsolver.hh
ewoms/linear/combinedcriterion.hh
ewoms/linear/convergencecriterion.hh
ewoms/linear/fixpointcriterion.hh
ewoms/linear/istlpreconditionerwrappers.hh
ewoms/linear/istlsolverwrappers.hh
ewoms/linear/overlappingbcrsmatrix.hh
ewoms/linear/parallelamgbackend.hh
ewoms/linear/parallelbasebackend.hh
ewoms/linear/parallelbicgstabbackend.hh
ewoms/linear/parallelistlbackend.hh
ewoms/linear/residreductioncriterion.hh
ewoms/nonlinear/newtonmethod.hh

this gets rid of quite a bit of copy-and-pasted code, replaces the "equation weight vector" for the  combinedCriterion class by rescaling the linear system of equations to be solved, improves the API and class names of the convergence criteria with an eye on performance and puts the preconditioner- and solver wrappers into separate files.
note that with this the prestine linear solvers from dune-istl now also respect the weight of equations (due to the rescaling the linear systems before solving them). Interestingly, the prestine dune-istl solvers do not seem to profit from this performance-wise while the home-brewn `BiCGStabSolver` seems to get 7 to 8% faster, probably because the `CombinedCriterion` performs better. This brings the performance advantage of `Ewoms::BiCGStabSolver` close …

Refactor the linear solver backends and the convergence criteria

---

ewoms/common/basicproperties.hh
ewoms/common/simulator.hh

the forced time steps are read from a file which is supposed to feature one time step size in seconds per line. this kludge is intended to ease debugging/comparisons, so it does not even attempt to cover any corner cases (like e.g. non-convergent time steps). given that this feature is turned of by default, it should not hurt anyone to have it?!

simulator: add a way to force the time step sizes externally

---

doc/handbook/build-handbook.sh
doc/handbook/ewoms-handbook.tex
doc/handbook/fluidframework.tex
doc/handbook/models.tex
doc/handbook/newton-in-a-nutshell.tex

TeXLive 2016 complains about \it and \bf.
Also, this patch adds a simple bash script to create the handbook from its LaTeX sources. Note that this script does *not* attempt to detect if all prerequisites (in terms of binaries and LaTeX packages) are properly available.

make the handbook compile on modern LaTeX distributions

---

doc/handbook/build-handbook.sh
doc/handbook/ewoms-handbook.tex

this gets rid of the ugly red and green boxes around references. Note that for some reason, hyperlinks do not seem to work anyway and that using pdflatex directly does not work either :/

handbook: use more sensible options for the hyperref package

---

ebos/eclcpgridmanager.hh

Due to the nature of CpGrid (manages one shared pointer to the equil/global grid and after load balancing another one to the distributed grid) simply copying the grid before load balancing should be faster as it only adjusts one shared pointer.

Use copy instead of processing eclipse data for duplicating grid.

---

ebos/collecttoiorank.hh

I assume that is what the code should do. Not 100% sure though.
It also closes #105 by actually resizes the arrays we store values using random access in.

Sets up a correct map from element to interior element index.

---

ebos/collecttoiorank.hh

Might save some time, space, and suprises.
Completes #137. @andlaus merges faster than I commit.

Switch of collecting data in non-parallel run.

---

ewoms/disc/common/fvbaseintensivequantities.hh
ewoms/linear/domesticoverlapfrombcrsmatrix.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/discretefracture/discretefractureintensivequantities.hh
ewoms/models/flash/flashintensivequantities.hh
ewoms/models/immiscible/immiscibleintensivequantities.hh
ewoms/models/ncp/ncpintensivequantities.hh
ewoms/models/pvs/pvsintensivequantities.hh
ewoms/models/richards/richardsintensivequantities.hh
ewoms/models/stokes/stokesintensivequantities.hh

this PR fixes a few warnings that are produced by GCC if it is passed `-Wextra` and removes the "evaluation point" concept from the intensive quantities. the latter potentially makes things a tiny bit faster because eight bytes are shoved of the intensive quantities object.

Fix extra warnings

---

ewoms/linear/istlsolverwrappers.hh
tests/problems/groundwaterproblem.hh

this fixes a small build issue in the wrappers of the solvers which are generated by the `EWOMS_WRAP_ISTL_SOLVER()` macro. it also changes the test for the groundwater problem to use such a solver.

Fix istl solverwrapper build

---

ebos/eclbasegridmanager.hh

i.e., add the PARSE_MISSING_DIMS_KEYWORD option. this was a recent change in flow_legacy.

ebos: sychronize the parse context with the one used by flow_legacy

---

ebos/eclproblem.hh
ebos/eclthresholdpressure.hh

the deck object currently does not provide a way to auto-generate an all-defaulted keyword if it has not been mentioned in the deck, so only access the keyword object if it is present.
possibly, this information is also exposed by EclipseState, but I have not found anything suitable.
@atgeirr: please merge if this fixes/improves the issues you've recently had.

ebos: no longer fail if the EQLDIMS keyword is not explicitly mentioned in the deck

---

ebos/collecttoiorank.hh

Previously distributedCartesianIndex was resized and afterwards all
entries were added with push_back. Therefore the array was twice as
big as expected and contained wrong values in the front.
With this commit we insert the values using random access. Thus the
size is as expeceted and the index of the entries do not depend on the
order of the grid traversal.
This is yet untested.

Fixes pushing to resized array distributedCartesianIndex.

---

CMakeLists_files.cmake

Without this we will also find generated test files in build directories
located below the source directory. This happens each time cmake run and
thus the list will increase due to recursiveness.
With this commit we only search for file below tests.
Closes #148

Only search for test file under tests.

---

ebos/ertwrappers.hh

See: https://github.com/OPM/opm-output/pull/176
But - I must admit I was dumbfounded when I stumbled across this code; as it says in a comment: "This code has shamelessly been copy pasted from opm-core". Since then the code in question has been moved to opm-output and refactored massively. I would assume the copy here in ewoms code can and should be retired?

Adapt to change in ert ecl_type.

---

ebos/collecttoiorank.hh

Correct version of #137 that gets reverted with this PR,
When comparing the code with `ParallelDebugOutput.hh` (the source for copy and paste) I realized that #137 must be wrong as these arrays get passed to `P2PCommunicator` and therefore should look the same in both cases.
I conclude that reserving memory instead of resizing the vector was correct, but we have to use `push_back` to populate the vector to get a list of interior element indices. That is the input P2PCommunicator seems to need.
@dr-robertk should probably have a look at this, too.
Patch is tested together with #140 that I will open again as it is needed, too.

localIndexMaps in CollectToIORank need to be lists of interior element indices.

---

ewoms/common/parametersystem.hh

It is used here but not included. The problem surfaced when I
had to change inclusion order in opm-simulators for debugging.

Add include of opm/common/Unused.hpp

---

ebos/eclproblem.hh

in the parallel case, this avoids the participating processes from desyncronizing if the solution is consistent on all processes.

ebos: hysteresis needs to be updated for all elements

---

ebos/eclproblem.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh

if the initial solution is explicitly given by the deck using the PRESSURE, SWAT, etc. keywords, the specified state can be thermodynamically impossible. To avoid inconsistencies, we use a flash calculation to find a state that is in thermodynamic equilibrium and exhibits the same masses as the explicitly specified solution. Since the flash solver needs to compute quantities for all fluid phases, but two-phase blackoil simulations usually do not specify the properties of one phase, the flash solver crashed. This patch works around that
issue by simply not using the flash solver in the twophase case, i.e., the explicit initial condition must be thermodynamically consistent in order to produce the stable results for a different choice of primary variables.
@akva2: If Jenkins is happy and …

make explicit initialization for twophase cases work

---

ebos/eclcpgridmanager.hh

this was found using GCC-7's address sanitizer. I suspect that this did not surface earlier (i.e., with valgrind), because newly allocated memory gets initialized to zero by the operating system, so the value
of the pointer was zero and the delete operator did what was right by coincidence. the new asan seems to initialize memory randomly, though.
i also tried to fix this using `std::unique_ptr`, but this seems to suffer from the same problem. maybe it is a bug in GCC-7's unique_ptr implementation.
lacking objections I'll cherry-pick this patch into the release branch.

EclCpGridManager: do not delete unintialized pointers

---

ewoms/common/propertysystem.hh
ewoms/disc/common/fvbaseproblem.hh

these leaks are not very important because these objects are de-facto singletons, i.e., they usually get allocated only once per invocation of the program.

fix some mild memory leaks found by ASAN

---

ewoms/io/vtkmultiphasemodule.hh

this is supposed to be a loop over all spatial axis, not over the fluid phases. the latest GCC from SVN rightfully complains about this. the error has not been discovered earlier because VTK velocity output is disabled by default and also, it worked "by coincidence" if the number of fluid phases was equal to the number of spatial dimensions.

VtkMultiphaseModule: fix incorrect loop variables

---

ebos/eclfluxmodule.hh
ebos/eclpeacemanwell.hh
ebos/eclproblem.hh
ewoms/io/vtkblackoilsolventmodule.hh
ewoms/models/blackoil/blackoildarcyfluxmodule.hh
ewoms/models/blackoil/blackoilextensivequantities.hh
ewoms/models/blackoil/blackoilindices.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoilproblem.hh
ewoms/models/blackoil/blackoilproperties.hh
ewoms/models/blackoil/blackoilsolventmodules.hh
ewoms/models/common/energymodule.hh
ewoms/models/common/multiphasebaseextensivequantities.hh

This adds an "ECLIPSE-style" extension of the black oil model for an additional "solvent" component. Conceptually this is IMO pretty questionable, since it adds a second "gas phase" that does not mix with "ordinary" gas. I suppose the reason why this extension was conceived by E100 is that if all you have is hammer, everything looks like a nail...
Functionality-wise, this patch is still not fully complete because miscibility of the solvent "phase" is not yet implemented. As far as I can see, the API changes required by miscibility are quite limited, though.
this PR depends on OPM/opm-material#229

blackoil: implement the immiscible solvent extension

---

ebos/ecltransmissibility.hh

the NTG value for active cells in the topmost layer was always 1.0. This resulted in some deviations in the transmissibilities of the Norne deck which lead the init file comparison unit tests from opm-simulators to fail.

ebos: fix the NTG averaging code

---

ewoms/disc/common/fvbaseintensivequantities.hh
ewoms/io/vtkmultiphasemodule.hh
ewoms/io/vtkprimaryvarsmodule.hh

this PR contains a minor cleanup of the FV base intensive quantities to reduce of manual fiddling if changing the attributes and -- more importantly -- it enables to write the extrusion factor of DOFs to the VTK files so that they can be inspected visually.

Write extrusion factor

---

ebos/eclproblem.hh

this reduces the number of direct deck accesses in `EclProblem` in favour of `EclipseState`-grid properties. as far as i can see, directly using the deck object cannot fully be avoided because `EclipseState` does not seem to provide internalized versions of all these keywords yet.

ebos: reduce direct deck usage

---

ebos/eclproblem.hh

one must use eclProps.getDoubleGridProperty() while the has() method is called eclProps.hasDeckDoubleGridProperty() (mind the Deck!).
this fixes #191.

ebos: fix the compilation

---

CMakeLists.txt

the build system recently renamed ERT_FOUND to ECL_FOUND which silently disabled the compilation of ebos and thus lead to some incorrect changes to be merged.
this would have avoided the havoc caused by #189.

ebos: build it if possible

---

ebos/eclproblem.hh

this adds support for the ROCKOPTS keyword to ebos and it exports the array of PVT region numbers for the compressed grid.
note that the ROCKOPTS stuff accesses the deck object directly because -- as far as I can see -- this keyword is not internalized by EclipseState yet.
I've tested this on norne and it did not seem to change anything.

add ROCKOPTS support

---

ebos/eclproblem.hh
ebos/ertwrappers.hh

Downstream of: https://github.com/OPM/opm-parser/pull/1092

Using std::time_t from TimeMap

---

ewoms/io/vtkblackoilsolventmodule.hh

this is kind of trivial, but if you want paraview not to be confused about the files produced with this it is critical.

fix some field names of the VTK output module for the solvent blackoil model extension

---

ebos/eclfluxmodule.hh
ebos/eclproblem.hh
ewoms/io/vtkblackoilpolymermodule.hh
ewoms/models/blackoil/blackoildarcyfluxmodule.hh
ewoms/models/blackoil/blackoilextensivequantities.hh
ewoms/models/blackoil/blackoilindices.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilpolymermodules.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoilproblem.hh
ewoms/models/blackoil/blackoilproperties.hh

Adds a conservation equation for polymer.
Polymer concentration in the water phase is used as primary variable
The polymer influences the viscosity of the water, and leaves gas and oil
unaffected. 
Shear effects can be modeled using the PLYSHLOG and SHRATE keywords.

Add polymer module in ebos

---

ewoms/models/blackoil/blackoilpolymermodules.hh

it seems like GCC 4.8.1 does not support `auto`-typed parameters for lambda functions.

fix build on travis

---

ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoiltwophaseindices.hh

This PR fixes several issues with the BlackoilModel when the number of phases is hardcoded to 2 for efficiency of two-phase cases.

Make BlackoilModel work for two-phases with hardcoded numPhases.

---

ebos/ecltransmissibility.hh
ewoms/nonlinear/newtonmethod.hh

i.e., they can be included without having other files included before them.

make all headers autonomous again

---

ewoms/common/conditionalstorage.hh
ewoms/disc/ecfv/ecfvstencil.hh

this is IMO quite a bit more intuitive because this class is a layer of indirection in front of some object, i.e., it can be regarded as a smart pointer.

ConditionalStorage: Switch it to pointer semantics

---

ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/discretefracture/discretefractureintensivequantities.hh
ewoms/models/flash/flashintensivequantities.hh
ewoms/models/immiscible/immiscibleintensivequantities.hh
ewoms/models/ncp/ncpintensivequantities.hh
ewoms/models/pvs/pvsintensivequantities.hh
ewoms/models/richards/richardsintensivequantities.hh

after OPM/opm-material#242, using memcpy() for this does not yield any performance benefit anymore but it may cause trouble in the future if some models do not use trivially copyable intensive quantities. (this
should probably be avoided for performance reasons, but the proper way to do this is to do this explicitly, i.e., using std::is_trivially_copyable)

remove the specialized copy constructors and copy operators from all IQ classes

---

ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaselocalresidual.hh
ewoms/disc/common/fvbaseproperties.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilproperties.hh
ewoms/models/blackoil/blackoilsolventmodules.hh

A Tag that enables surface volume scaling is added to the property
system.
NEW_PROP_TAG(EnableSurfaceVolumeScaling);
If enabled the blackoil equations will be formulated in terms of surface
volumes instead of mass/volume.

Make it possible to formulate the blackoil eq in terms of surfacevolumes

---

ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh

Changes
- water only case is treated separately
- an epsilon can be added to restrict the switching. Useful to avoid
oscillating between primary variable meaning
- call the method recursively since a variable switch may occur more than
once at a time
Testing 
Pass all tests in ewoms 
Runs SPE9 fine with ebos. 
Tested in combination with flow_ebos on SPE9, Norne, Model2-0 and Model2-5
Tested with flow_ebos_solvent

Improve the adaptPrimaryVariables code

---

ebos/eclbasegridmanager.hh
ebos/eclproblem.hh
ewoms/common/parametersystem.hh
ewoms/common/simulator.hh

This PR enables the ability to create the Opm::Deck and Opm::EclipseState outside of the EbosSimulator. The default behavior is unchanged.

Allow parameters to be passed to Simulator.

---

CMakeLists.txt
ewoms/common/parametersystem.hh
ewoms/common/propertysystem.hh
tests/lens_immiscible_ecfv_ad.hh
tests/lens_immiscible_ecfv_ad_cu1.cc
tests/lens_immiscible_ecfv_ad_cu2.cc
tests/lens_immiscible_ecfv_ad_main.cc

so far, the linker bailed out due to duplicate definitions of variables if multiple compile units used the same type tag. This is problematic if the sources are split into separate compile units and that use the same type tag; in particular, this applies for traditional libraries.
Due to various C++ peculiarities, this patch complicates the internal implementation of the property system quite a bit, but given that the usage of it (as well as the compile time) stay unchanged, I do not
consider this to be a big problem. Note that the introspection code is particularly problematic because it needs static initializers that do not cause the linker to choke in the case of multiple compile units.
Finally, to prevent future regressions, this patch adds a unit test for the lens problem which uses …

make the property system work with multiple compile units

---

ewoms/models/pvs/pvsratevector.hh

The setMassRate function accesses the wrong index of the pvsRateVector.

Bug fix for pvsratevector indices in setMassRate function

---

ewoms/models/blackoil/blackoilindices.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilpolymermodules.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoiltwophaseindices.hh

- method for mapping from canonicalToActiveComponentIndex() is added
- guards are added to avoid access to non present components.

Fix to make 2p gasoil and wateroil compile and run

---

debian/control
debian/rules

also disable testing in packaging.
the test target in ewoms is rather broken, and incompatible with
packaging.

update packaging to reflect new libecl

---

ebos/ebos.cc
ebos/eclbasegridmanager.hh
ebos/eclproblem.hh
ewoms/common/parametersystem.hh
ewoms/common/simulator.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaseproperties.hh
ewoms/io/basegridmanager.hh
ewoms/models/blackoil/blackoiltwophaseindices.hh

This gets rid of some special-purpose code in generic places (i.e. the `SimulatorParameter` class) and no special hacks to the property and parameter system are required anymore.

ebos: simplify passing of pre-parsed ECL decks

---

ebos/ebos.cc
ebos/eclbasegridmanager.hh
ebos/eclproblem.hh
ewoms/common/simulator.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaseproperties.hh
ewoms/io/basegridmanager.hh

since OPM/opm-simulators#1287 has been merged there are no "in tree" OPM upstreams which use that mechanism anymore.

remove the deprecated SimulatorParameter mechanism

---

ewoms/common/parametersystem.hh
ewoms/common/start.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaselinearizer.hh

This makes multi-threaded linearization with OpenMP  work. (note that the linear solver is a quite different beast.)
this issue was only uncovered because the dune buildsystem branches (OPM/opm-common#277 et al) support enabling OpenMP without too much hassle. (I always had major headaches to get OpenMP into working conditions with the current build system.)

Fix OpenMP

---

CMakeLists.txt

Another shenanigan of the current default OPM build system:
this produced a cmake syntax error if ewoms was compiled with only the mandatory opm modules available because some *_FOUND variables expand to the empty string instead of to "0" in this case.

fix the build condition for ebos

---

ebos/eclequilinitializer.hh

Do not relay on opm-core objects like phaseUsage and BlackoilState but
instead use the initializer directly.
Depents on OPM/opm-core#1187

Use the Equil initializer directly

---

ebos/eclthresholdpressure.hh

Verified on Model 2 rel 0 with 1, 2, 4 and 8 cores.  
THPRESS and end results are identical in eyeball norm between the runs.

BUGFIX Communicate the default thpress correctly 

---

ebos/ecloutputblackoilmodule.hh

this quantity is pretty useless, and the analogous one for wet gas was never written...

black-oil: do not write the saturated oil formation factor to VTK anymore

---

ewoms/models/blackoil/blackoilprimaryvariables.hh

if the interpretation of the primary variables has been changed and the new variables have been set correctly, there must not be any further changes without an update.

BlackOilPrimaryVariables: remove recursion adaptPrimaryVariables()

---

INSTALL
debug-clang.opts
debug-gcc.opts
debug.opts
optim-clang.opts
optim-gcc.opts
optim.opts

the dunecontrol option files should now usually work even with "unwrapped" cmake, i.e. if opm-dune-cmake was not found.

update the build instructions and slightly improve the dunecontrol option files

---

ewoms/io/vtkenergymodule.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilproperties.hh
ewoms/models/common/energymodule.hh
ewoms/models/common/multiphasebasemodel.hh
ewoms/models/common/multiphasebaseproblem.hh
ewoms/models/common/multiphasebaseproperties.hh
ewoms/models/discretefracture/discretefractureproblem.hh
ewoms/models/flash/flashboundaryratevector.hh
ewoms/models/flash/flashlocalresidual.hh
ewoms/models/flash/flashproperties.hh
ewoms/models/immiscible/immiscibleboundaryratevector.hh
ewoms/models/immiscible/immisciblelocalresidual.hh
ewoms/models/ncp/ncpboundaryratevector.hh
ewoms/models/ncp/ncplocalresidual.hh
ewoms/models/pvs/pvsboundaryratevector.hh
ewoms/models/pvs/pvslocalresidual.hh
tests/problems/co2injectionproblem.hh
tests/problems/cuvetteproblem.hh
tests/problems/fractureproblem.hh
tests/problems/infiltrationproblem.hh
tests/problems/obstacleproblem.hh
tests/problems/waterairproblem.hh

according to wikipedia the term "heat" is the energy transferred due to a temperature gradient, i.e., it only makes sense if such a gradient is present and this is not necessary for the storage term.
this means that technically the term "heat conductivity" is meaningful, but "thermal conductivity" is IMO more consistent.
this has partially already been done in opm-material and eWoms it was pretty inconsistent, so it also depends on OPM/opm-material#273.

consistently rename "heat conduction" to "thermal conduction" and use "solid energy" laws

---

ebos/eclsummarywriter.hh

currently the ewoms output code relies on the outdated HAVE_ERT define.
this is only set through the opm-core dependency. if you build without,
you cannot build ewoms. this at least fixes the build in this situation, although we do not get the output code enabled in that case.

fixed: build without opm-core

---

ewoms/models/blackoil/blackoilprimaryvariables.hh

this makes flow work for SPE1CASE1 (actually, I do not really know why), but it might lead to different convergence behaviour in some cases.
@totto82: can you test and assess?

Revert "add back the epsilon value when switching from {oil,gas}-only to both hydrocarbon phases"

---

ebos/eclproblem.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh

this is the downstream mop-up of OPM/opm-material#278

adapt to the reordering template arguments of get*_(fluidState) in opm-material

---

ewoms/disc/common/fvbaseextensivequantities.hh
ewoms/models/common/darcyfluxmodule.hh
ewoms/models/common/forchheimerfluxmodule.hh
ewoms/models/common/multiphasebaseextensivequantities.hh
ewoms/models/flash/flashboundaryratevector.hh
ewoms/models/flash/flashextensivequantities.hh
ewoms/models/immiscible/immiscibleboundaryratevector.hh
ewoms/models/immiscible/immiscibleextensivequantities.hh
ewoms/models/ncp/ncpboundaryratevector.hh
ewoms/models/ncp/ncpextensivequantities.hh
ewoms/models/pvs/pvsboundaryratevector.hh
ewoms/models/pvs/pvsextensivequantities.hh
ewoms/models/richards/richardsboundaryratevector.hh
tests/problems/fingerproblem.hh
tests/problems/fractureproblem.hh
tests/problems/groundwaterproblem.hh
tests/problems/infiltrationproblem.hh
tests/problems/lensproblem.hh
tests/problems/obstacleproblem.hh
tests/problems/outflowproblem.hh
tests/problems/powerinjectionproblem.hh
tests/problems/reservoirproblem.hh
tests/problems/richardslensproblem.hh
tests/problems/waterairproblem.hh
tutorial/tutorial1problem.hh

instead of passing a "minimal" fluid state that defines the thermodynamic conditions on the domain boundary and the models calculating everything they need based on this, it is now assumed that all quantities needed by the code that computes the boundary fluxes are defined. This simplifies the boundary flux computation code, it allows to get rid of the `paramCache` argument for these methods and to potentially speed things up because quantities do not get re-calculated unconditionally.
on the flipside, this requires slightly more effort to define the conditions at the boundary on the problem level and it makes it less obvious which quantities are actually used. That said, one now has the
freedom to shoot oneself into the foot more easily when specifying boundary conditions and also tools …

refactor the boundary condition handling slightly

---

CMakeLists.txt
CMakeLists_files.cmake
ebos/collecttoiorank.hh
ebos/ecloutputblackoilmodule.hh
ebos/eclproblem.hh
ebos/eclwriter.hh
tests/data/summary_deck_non_constant_porosity.DATA
tests/test_ecl_output.cpp

This PR build on #272 and makes the old PR absolute.  
1) EGRID and INIT output is added to new output module ebos
2) Adds option for double_si restart output
3) Compute region FIP and block values on each core and communicates the results instead of depending on these being computed by opm-output
4) Only compute and communicate values asked for by the deck. 
Depends on OPM/opm-grid#302, OPM/opm-output#235
and needs update in opm-simulator. 
TODO:

FluidInPlace, INIT and EGRID output to Ebos

---

ebos/eclalugridmanager.hh
ebos/eclbasegridmanager.hh
ebos/eclcpgridmanager.hh
ebos/eclpolyhedralgridmanager.hh

reason is that we need to remove some completions in the Well in the Schedule due to processed grid in opm-simulators.

removing the completions in inactive cells after createGrid() in eclbasegridmanager

---

ewoms/models/blackoil/blackoiltwophaseindices.hh

It is intended to making the oil water polymer simulation (OPM/opm-simulators#1416) work. 
The approach is suggested by @totto82

fixing polymerConcentrationIdx in blackoiltwophaseindices

---

ebos/ecloutputblackoilmodule.hh
ebos/eclwellmanager.hh
tests/test_quadrature.cc

i.e. on ICC. the compiler is right in producing warnings here, though.

fix a few "unused variable" warnings that occur on more uncommon compilers

---

INSTALL

this is required because opm-parser is no longer a thing.

update the installation instructions

---

ebos/alucartesianindexmapper.hh
ebos/collecttoiorank.hh
ebos/ecloutputblackoilmodule.hh
ebos/eclwriter.hh
ewoms/linear/istlpreconditionerwrappers.hh
ewoms/linear/overlappingbcrsmatrix.hh
ewoms/linear/parallelamgbackend.hh
ewoms/linear/parallelbasebackend.hh
ewoms/linear/parallelistlbackend.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilpolymermodules.hh
ewoms/models/ncp/ncpnewtonmethod.hh
tests/problems/waterairproblem.hh

This fixes the build on the latest master version of Dune  (i.e., what is most likely to become Dune 2.7). Probably this needs to be revised when Dune 2.7 gets released, but the changes are beneficial on their own and they're also not very complicated.

Fix dune master

---

ewoms/models/common/energymodule.hh

... even if energy conservation is disabled. The rationale is to allow  to allow constructs like
```
if (enableEnergy)
rate[energyEqIdx] = 123.456;
```
on the flipside, this approach leads to runtime errors if the guard is forgotten and energy is disabled. That said, these errors are most likely going to be segmentation faults and should be quite easily to spot and to fix.

always define an index for the energy equation

---

ebos/eclwriter.hh
ewoms/parallel/tasklets.hh

this has been quite a bit more complicated than I initially thought.

generalize the tasklet mechanism to an arbitrary number of worker threads

---

ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbasenewtonconvergencewriter.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/disc/common/fvbaseproperties.hh
ewoms/io/vtkmultiwriter.hh
ewoms/parallel/tasklets.hh

`Dune::VTKWriter` seems to be on the rather slow side, so threaded output writing leads to a sizeable speedup for the VTK format. For situations where an extra thread is not desireable, asynchronous VTK
output can be disabled using the `--enable-async-vtk-output=false` command-line parameter.
The main complication of this is that `Dune::VTKWriter` cannot be used in conjunction with MPI-parallel simulations because there are unnecessary calls to `MPI_barrier()` in `Dune::VTKWriter::pwrite()`
which lead to all kinds of fun since multiple threads are doing uncoordinated MPI calls in that case. (This is because the main thread needs to call MPI functions during e.g. the linear solver.) That said,
for the MPI-parallel simulations which I've tested, there was no speedup either, so asynchronous …

write the VTK output asynchronously by default for sequential simulations

---

tests/test_ecl_output.cc

this lead to non-deterministic crashes deep inside libecl. My cursory hypotheses are that this test makes the assumption that the output is written synchronously (it tries to read back the results from disk immediately) and/or that libecl is not threadsafe.

disable asynchronous output for the ECL output test

---

ewoms/disc/common/fvbaselocalresidual.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/common/darcyfluxmodule.hh

besides being briefer, this also ensures that derivatives are finite.

use Opm::isfinite() instead of std::isfinite(Opm::value())

---

ebos/eclequilinitializer.hh
ebos/eclfluxmodule.hh
ebos/eclpeacemanwell.hh
ebos/eclproblem.hh
ebos/ecltransmissibility.hh
ebos/eclwellmanager.hh
ebos/equil/initstateequil.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaselocalresidual.hh
ewoms/disc/common/fvbaseprimaryvariables.hh
ewoms/disc/ecfv/ecfvstencil.hh
ewoms/io/vtkblackoilenergymodule.hh
ewoms/models/blackoil/blackoilboundaryratevector.hh
ewoms/models/blackoil/blackoilenergymodules.hh
ewoms/models/blackoil/blackoilextensivequantities.hh
ewoms/models/blackoil/blackoilindices.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilnewtonmethod.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoilproblem.hh
ewoms/models/blackoil/blackoilproperties.hh
ewoms/models/blackoil/blackoilratevector.hh
ewoms/models/blackoil/blackoiltwophaseindices.hh

this implements an energy conservation extension for the black-oil model. It requires some small downstream mop-up because the indices class expects an additional template argument which specifies if energy is enabled or not.
I've verified that the performance of `flow` for norne does not change with this. Further testing is highly appreciated, though.

Implement blackoil energy

---

ebos/eclproblem.hh
ewoms/common/propertysystem.hh
ewoms/models/blackoil/blackoilenergymodules.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh

this PR contains two relative straight-forward changes: the first is a work around for a likely `constexpr` related compiler bug of older GCC versions, the second fixes https://github.com/OPM/opm-simulators/issues/1453. I think both should be part of the 2018.04 release.
thanks goes to @bska for finding the issue with initial temperature.

ebos fix and compiler workaround

---

ewoms/models/blackoil/blackoilpolymermodules.hh

it was removed accidently in https://github.com/OPM/ewoms/pull/298.

fixing the polymer running for cells without water

---

ewoms/parallel/tasklets.hh
tests/test_tasklets.cc

this PR adds a few minor improvements to the tasklet mechanism. in particular, the there now is the concept of a "worker thread index", which should make it relatively straight-forward to replace OpenMP by tasklets.

Improve tasklets

---

ebos/ecloutputblackoilmodule.hh

Reason: use the same output name as eclipse. 
Need an update of ref. data in opm-tests before merging!

change ecl output name from SSOL to SSOLVENT

---

ebos/femcpgridcompat.hh
ewoms/disc/common/fvbaseprimaryvariables.hh

The specialization of FieldTraits for the PrimaryVariables was missing. This patch implements them for all PrimaryVariables in eWoms based on FieldVector.

[bugfix][PrimaryVariables] Implement FieldTraits for PrimaryVariables

---

ebos/femcpgridcompat.hh

This code has been previously moved to opm-material and accidentally came into the code from the last merged request since this section is not tested since it depends on optional thrid party modules.

[bgufix][femcompat] remove operator << and operator >> for __float128

---

ewoms/common/parametersystem.hh
ewoms/common/start.hh

i.e. they are still there but not mentioned in the usage message. only registered parameters can be hidden an only before the parameter registration is closed by EWOMS_END_PARAMETER_REGISTRATION.

parameter system: add ability to hide parameters

---

ewoms/common/parametersystem.hh

this lead to undefined symbols for binaries that use EWOMS_HIDE_PARAM() when using debugging flags on GCC. They where caused by trying to take references to the values of some properties and these values are `static const int` class attributes. Since I'm pretty sure that the c++ standard mandates that symbols for such variables must be emitted, this might constitute a GCC bug. (also, when optimizations are enabled the linker errors went away. this was probably caused by the fact that this variable was unused and the compiler thus probably killed it completely.)

fix linkage of binaries that use EWOMS_HIDE_PARAM()

---

ebos/eclproblem.hh
ebos/eclthresholdpressure.hh
ebos/eclwriter.hh

THPRES is read from the restart file
We no longer need to compute it from the initial conditions if defaulted.
Currently the restart of Model 2 doesn't work due to issues with THPRES input. 
This PR fixes this, but there is a slight difference in results. I have compared the
computed thpressures with the ones read from the restart file and they are identical as far as I can see. 
I will need to do some more testing to figure out whether the mis-match is related to THPRES or to something els.

WIP Fix thpress restart

---

ewoms/common/parametersystem.hh
ewoms/common/quadraturegeometries.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/models/blackoil/blackoilenergymodules.hh
ewoms/models/blackoil/blackoilsolventmodules.hh
tests/lens_immiscible_ecfv_ad_cu1.cc
tests/problems/reservoirproblem.hh
tests/test_ecl_output.cc
tests/test_equil.cc
tests/test_tasklets.cc
tutorial/tutorial1problem.hh

this is only relevant people who are masochistic enough to go beyond `-Wall`. (note that at this warning level, there is plenty of noise from Dune and other upstream dependencies.)

fix extra compiler warnings

---

ewoms/common/simulator.hh

this allows external users like `flow` to make the execution timer return accurate timings. In `flow`'s case this is useful to implement stuff like the `TCPU` output field.

simulator: provide a mutable version of Simulator::executionTimer()

---

ewoms/linear/parallelbasebackend.hh

as usual, `flow` is completely unaffected by this because it does not use this code.

linear solvers: reduce the singularity limit to 10^-30

---

ewoms/disc/common/fvbaseproblem.hh

this is mainly relevant for situations which use a non-eWoms timeloop yet the size of the next time step ought to be available via the usual mechanisms. (i.e. for implementing "perfect" restarts using the ECL format.)

problems: allow imposing the size of the next time step externally

---

ebos/collecttoiorank.hh
ebos/eclcpgridvanguard.hh
ebos/eclpeacemanwell.hh
ebos/eclproblem.hh
ewoms/disc/common/fvbaselinearizer.hh
ewoms/nonlinear/newtonmethod.hh

this PR makes ebos work properly in the MPI-parallel case. if the `matrix_add_well_contributions` is not explicitly set to `true`, `flow` is completely unaffected because it currently rolls its own code when it comes to wells.
Besides the parallelization fixes, the PR contains some smaller cleanups (removal of the unused EQUIL grid, cleanup of `CollectToIORank` and the removal of the `ExportGlobalTransmissibility` properties) that have been missed during previous refactorings... (the removal of `ExportGlobalTransmissibility` requires OPM/opm-simulators#1533, but OPM/opm-simulators#1533 can be merged independently of this PR)

ebos: fix parallel

---

ebos/ecloutputblackoilmodule.hh
ebos/eclproblem.hh
ebos/eclwriter.hh

this adds a `writeOutput()` method to `EclProblem` which extracts all relevant reservoir and well data from the appropriate eWoms objects. `flow` doesn't use this, so it is unaffected.
the second patch removes the `#if HAVE_ECL_{IN,OUT}PUT` guards because `ebos` will not be useful without them. (probably it does not even compile.)

Improve ebos ECL I/O

---

ewoms/models/blackoil/blackoilmodel.hh

all of these warnings are harmless and only appear with non-standard flags.

black oil model: fix some annoying signeness compiler warnings

---

ebos/ecloutputblackoilmodule.hh
ebos/eclwriter.hh

this significantly reduces the noise level of debug files if the FIP values are not of interest.
note that until OPM/opm-simulators#1512 gets merged this feature is not usable from `flow`.

ebos: add possibility to disable the FIP output even if requested in the deck

---

ewoms/linear/combinedcriterion.hh
ewoms/linear/residreductioncriterion.hh
ewoms/linear/weightedresidreductioncriterion.hh

some header guard macros were not adapted after copying the respective source files and ´WeightedResidualReductionCriterion::update()` was not adapted after the signature of the method changed in the base class. the practical implications of this were limited, because the affected convergence criteria are not used by default. i.e., currently they are purely used for debugging purposes.
as usual, `flow` is unaffected  by these changes. Somewhat unusually, the other binaries in eWoms also are supposed to not care...

fix up the more uncommon convergence criteria for the default linear solver

---

ewoms/models/blackoil/blackoilnewtonmethod.hh

these changes bring the update routines of `ebos` closer to those of `flow`:
- limit pressure changes to 30% of the absolute value
- use a scaling factor for saturations to implement the Appleyard-chop. this is slightly more complicated than the previous code but it has the advantage that changes to the oil phase saturation also get limited.
`flow` currently uses completely separate code paths, so it is unaffected.

Black oil model: improve update

---

ewoms/linear/parallelbasebackend.hh

while the rescaling does not change anything mathematically, it confuses some preconditioners, in particular those which make assumptions on the semantics of a given equation.
the rescaling could either happen at model level or within a specialized linear solver backend.
`flow` is unaffected by this because it rolls its own stuff when it comes to the linear solver. the eWoms tests seem to exhibit a small performance increase on average. (most tests become faster, though some get slightly slower.)

linear: do not rescale the linear system of equations before solving

---

bin/runtest.sh
ebos/eclproblem.hh
ewoms/common/parametersystem.hh
ewoms/common/start.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/disc/ecfv/ecfvstencil.hh
ewoms/io/vtkscalarfunction.hh
ewoms/io/vtktensorfunction.hh
ewoms/io/vtkvectorfunction.hh

this PR switches the parameter file parser to a custom implementation (instead of using `Dune::ParameterTreeParser`) and it also contains a few smaller cleanups of the parameter system which should not affect the developer experience. the switch to a custom parser allows the key names that are put into the parameter files to be transformed, i.e.,
```
enable-vtk=true
```
is now also possible in parameter files whereas before only CamelCase parameter names like
```
EnableVtk=true
```
were valid. besides this, any valid Windows INI file that does not use parameter groups should be readable, i.e., semicolons are now also treated as a comment indicator.
Despite C++'s file and string processing tools being quite blunt IMO, I tried to keep the prerequisites minimal, i.e., this code does not use …

Use a custom parameter file parser

---

ebos/eclbasevanguard.hh
ebos/eclproblem.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbasenewtonconvergencewriter.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/disc/common/fvbaseproperties.hh
ewoms/io/restart.hh
ewoms/io/vtkmultiwriter.hh

all disc output, i.e. VTK, restart files, ECL and -- in the future -- logfiles, goes to that directory. before this, only the ECL output could be directed to a different than the current working directory and the parameter for this was called "EclOutputDir".
note that the Dune VTK writing infrastructure makes it harder than it needs to be: suddenly Dune::VTKWriter::write() does not work in parallel anymore, but Dune::VTKWriter::pwrite() must be called with the right arguments.
this PR requires a small mop-up PR in opm-simulators.

make the "OutputDir" parameter apply universally

---

ebos/eclproblem.hh

seems like I didn't compile #364 with pedantic warning flags enabled.

ebos: avoid sign-comparison warning

---

CMakeLists.txt
ewoms/disc/common/fvbasediscretization.hh
ewoms/parallel/threadmanager.hh

In particular this restores multithreading in e.g. flow without having to use --threads-per-process.
It still honors threads per process, and it still honors OMP_NUM_THREADS. so everybody should be satisfied.
Note I had to disable multithreading in some ewoms tests, as they break with it enabled.

Default number of threads to auto

---

CMakeLists.txt
ewoms/disc/common/fvbasediscretization.hh
ewoms/io/vtkmultiphasemodule.hh
ewoms/parallel/threadmanager.hh

this fixes a race condition in the VTK output code if intrinsic permeabilitiy tensors ought to be written. the reason was that Dune::DynamicMatrix::resize() is not threadsafe. now, we simply rely on the fact that the `Tensor` objects are assumed to be dim \times dim matrices by the base class anyway.
Further this PR reverts most of #370 and #371 because they break builds without OpenMP enabled and the threading mumbo-jumbo for flow is better done within opm-simulators.

Threading fixes

---

ebos/eclbasevanguard.hh
ebos/eclproblem.hh

before this patch the parameter was registered by the problem but not used there. Since this is quite confusing, let's move registration to where the parameter is actually used, i.e., the vanguard.
@joakim-hove: please press Green if you do not object to this.

move the registration of the EnableOpmRstFile to the EclBaseVanguard

---

ewoms/common/start.hh
ewoms/disc/common/fvbaselinearizer.hh

The handler for DuneException will be hidden behind the std::exception
and never be invoked. It should be moved up so that the most specific
exception is handled first.

Handle more specific exceptions first

---

ewoms/disc/common/fvbaselinearizer.hh
ewoms/parallel/tasklets.hh

Exceptions cannot escape from OpenMP threads to be handled at the outer
level in the master node. If an exception occurs and is not handled
within the parallel block, terminate() will be called!
This patch catches all exceptions that occurs in threads, tuck them away
and let the parallel block end normally. Afterwards one of the
exceptions are selected at random and then rethrown in single thread mode.
This implementation is perhaps the most elegant because the reduction happens in an OpenMP pragma, the cost is however that it now requires GCC 5.0 or later. We can implement the reducion explicitly with a critical section instead if that compiler requirement is not desirable; discussion in comments!

Handle exceptions throw in OpenMP threads

---

ebos/eclbaseaquifermodel.hh
ebos/eclproblem.hh

this is similar to the mechanism for well models: the API is defined here, but can be overloaded by downstream modules. In contrast to the well model where the default class follows a simplistic approach, the default class for aquifiers does nothing, i.e., the actual implemenentation must be provided by downstream.

ebos: add an API for aquifiers

---

ebos/eclequilinitializer.hh
ebos/eclproblem.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh

Depends on OPM/opm-material#310
Gives a small (5%) speed up in the linearizer for the Olympus case.

Blackoil: Prepare for 2p conditional storage of fluidstate

---

ewoms/models/blackoil/blackoilmodel.hh

The main change is that we now care quite a bit less about water than about the hydrocarbons. Also, the equation weight was inverted when conserving fluid surface volume instead of mass, oops. Note that the tolerances for oil, gas and water are now always expressed in terms of "invalid kg per second", i.e., the tolerances for the Newton-Raphson solver probably should be changed for problems that used the black-oil model formulated in terms of surface volumes.
this is only relevant for the eWoms Newton-Raphson solver, i.e. `flow` is completely unaffected at the moment.

blackoil model: fix the equation weights

---

ebos/ecloutputblackoilmodule.hh

This has annoyed me as well. 
Fix issue  OPM/opm-common#543

Avoid output of trivial fipnum regions

---

ewoms/disc/ecfv/ecfvstencil.hh

The SubControlVolume class in vertex-centered discretization has a
localGeometry method that was used in the diffusion module for free
flow boundary conditions, but there was no counterpart to this is the
Dune::Entity class, which is used for element-centered discretization.
Admittedly not knowing whether this is absolutely the same concept,
there is a geometryInFather method in the Dune::Entity class which
provides seemingly similar information.
With this patch, problems using element-centered discretizations can
thus be compiled with diffusion enabled. Testing has been minimal,
however.

Prov. localGeometry meth. for elem.-centr. discret.

---

ewoms/models/blackoil/blackoilenergymodules.hh
ewoms/models/blackoil/blackoilintensivequantities.hh

this ought to succeed #403. the difference is that porosity needs to be considered for energy storage, but compressibility as it is implemented by the blackoil model must not. as an approximation for reality we thus use the reference porosity instead of the current one.
@hnil: please press green if you agree.

Use reference porosity for rock energy storage

---

ebos/eclbasevanguard.hh

IMO the simulator should not be in the business of managing low-level parser objects in the first place, because that's what EclipseState is supposed to do?!
anyway, since these objects are not needed to decide which simulator to use, they are now always managed internally by the vanguard, i.e., setExternalDeck() does not take them anymore.
this needs a small mop-up in opm-simulators.

ebos: clean up the mess that is the schedule and summaryConfig objects a bit

---

ewoms/disc/common/fvbasediscretization.hh
ewoms/linear/parallelamgbackend.hh
ewoms/linear/parallelbasebackend.hh
ewoms/linear/parallelbicgstabbackend.hh

The magic value -1 indicates that a value based on an order less of the
Newton tolerance should be used. The special value 0. cannot be used to
signal this, as that value is already used to indicate that the
criterion should be deactivated; however there were no way of setting
this to zero before this change.
Credits belong to Tor-Harald, who realized that an over-eager
convergence check was the reason that the simulations didn't update.

Allow abs. tol. in linear solver to be set by prop

---

ewoms/disc/common/fvbaselinearizer.hh
ewoms/parallel/threadedentityiterator.hh

these exceptions must be handled within the loop over the grid, otherwise there will be a casualty amongst the threads.

fix the exception-handling-during-linearization code

---

ewoms/linear/parallelamgbackend.hh
ewoms/linear/parallelbicgstabbackend.hh

this was set to -1 by default because the computed value was not used anymore after ewoms#420. The automatically computed absolute tolerance now is also tighter than it was before which hopefully reduces issues.

fix the auto-determined absolute tolerance for the linear solver

---

ewoms/linear/matrixblock.hh

This fixes compilation issues mentioned in opm-simulators#1635.

[bugfix][MatrixBlock] fix fallout from SparseMatrixAdapter merge for DUNE 2.4.1.

---

ebos/ecloutputblackoilmodule.hh
ebos/eclpeacemanwell.hh
ebos/eclproblem.hh
ebos/ecltracermodel.hh
ebos/tracervdtable.hh
ebos/vtkecltracermodule.hh

reads tracer input from deck, solves tracer equation fully implicit as a post processing step in endTimeStep
tested on a simple modified SPE1CASE1 and NORNE deck and compared with eclipse
TODO: restart and parallel, summary output
Depends on OPM/opm-common#562

Add ecl tracer model

---

ebos/ecltracermodel.hh

Closes #438.
Since the merge of PR #431 I experienced compile errors with DUNE versions 2.4, 2.5, and current master.
The old version do not know SeqILU (added in 2.6) and for master an undefined typedef was used

Fix tracer code compilation for DUNE versions other than 2.6

---

ebos/ecloutputblackoilmodule.hh

Previously all processes reported
"Warning: Fast restart using SAVE is not supported. Standard restart file is written instead."
in the PRT file.
Now this is done only on the master process where logging is activated.

Do not log messages during getWriteRestartFile query on all procs.

---

ebos/eclproblem.hh
ebos/ecltracermodel.hh

The tracer model slows down the simulation time and is disabled by
default, until the performance is improved.

Add parameter for (dis)enable the tracer model

---

ebos/eclproblem.hh
ewoms/models/blackoil/blackoilindices.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilnewtonmethod.hh
ewoms/models/blackoil/blackoilpolymermodules.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoilproperties.hh
ewoms/models/blackoil/blackoiltwophaseindices.hh

The molecular weight will be used to evaluate the polymer viscosity based on a different viscosity model. 
This PR requires the upstream PR https://github.com/OPM/opm-material/pull/317 .

Extending the polymer module to handle the polymer molecular weight transport

---

ebos/eclproblem.hh
ewoms/disc/common/fvbaseelementcontext.hh
ewoms/disc/common/fvbaselocalresidual.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoilproblem.hh

some weird hacks (hello, DR[SV]DT) cause a change of the storage term in the first Newton-Raphson iteration compared to the solution of the previous time level. In order to use the correct values, one thus must explicitly recompute the storage term for the previous time step instead of just reusing the result of the first Newton-Raphson iteration of the current time step.
This (hopefully) fixes the root issue which is papered over  by #446. I've tested this on Norne and did not notice any performance regression. decks which have DRSDT or DRVDT active at some point may yield slightly different results, so a data update might be required.

make it possible to explicitly compute the storage term of the previous time step

---

ewoms/models/blackoil/blackoilpolymermodules.hh

this is required because of OPM/opm-material#319.

adapt to rename of XYTabulated2DFunction to IntervalTabulated2DFunction

---

ebos/eclbaseaquifermodel.hh
ebos/eclequilinitializer.hh
ebos/eclwellmanager.hh
ebos/eclwriter.hh
ebos/equil/initstateequil.hh
ewoms/disc/common/baseauxiliarymodule.hh
ewoms/disc/common/fvbaseconstraints.hh
ewoms/disc/common/fvbasegradientcalculator.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/io/dgfvanguard.hh
ewoms/io/vtkmultiphasemodule.hh
ewoms/linear/matrixblock.hh
ewoms/linear/overlappingbcrsmatrix.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoilpolymermodules.hh
ewoms/models/immiscible/immiscibleintensivequantities.hh
ewoms/models/richards/richardsintensivequantities.hh
tests/lens_immiscible_ecfv_ad_cu1.cc
tests/lens_immiscible_ecfv_ad_cu2.cc

the flags which I used are
```
-pedantic \
-Wall \
-Wextra \
-Wformat-nonliteral \
-Wcast-align
-Wpointer-arith \
-Wmissing-declarations \
-Wcast-qual \
-Wshadow
-Wwrite-strings \
-Wchar-subscripts \
-Wredundant-decls \
-fstrict-overflow \
-O3 \
-march=native \
-DNDEBUG=1
```
note that some heavy filtering is not the worst idea because DUNE is far from not emiting any warnings with these flags.
Also, there were some pesky warnings in test_ecl_output which I don't know how to fix:
```
tests/test_ecl_output.cc:218:73: warning: missing initializer for member ‘Opm::data::Connection::effective_Kh’ [-Wmissing-field-initializers]
```

fix some masochistic compiler warnings for the GCC 9 pre-release

---

ebos/eclbasevanguard.hh

Add a command-line option `--strict-parsing`. If the `--strict-parsing` option is enabled we all `ParseContext` error modes are treated with the mode `DELAYED_EXIT1` - this implies that:
1. All recognized error modes are treated as fatal.
2. Parsing, and construction of `EclipseState++` objects continues all the way (unless some other failure pops up); if there are errors - all errors and warnings are dumped on `stderr` and the application stops.
The first commit comes from: #453 - which must be merged first.
**Update:** This PR is not really complete, because the `Deck` and `EclipseState` objects are assigned from external scope, so the `--strict-parsing` option must be parsed/interpreted also in opm-simulators.

Strict parsing

---

ebos/eclnewtonmethod.hh
ebos/eclproblem.hh

this calculates the error and convergence differently from the standard Newton method.
for the limited number of cases that work with plain-ebos (i.e., SPE1 and SPE9), this resulted in a very sizeable speedup.

ebos: introduce an EclNewtonMethod

---

bin/runtest.sh

In particular:
- "wc -w" will have spaces in the output on BSD,
- "python" defaults to python 3, so we must explicitly invoke python2.
@andlaus I have not been able to verify that my changes also work on Linux, don't think Jenkins checks it? Or maybe it does?

Make runtest.sh also work on BSD/macOS.

---

ebos/eclfluxmodule.hh
ebos/eclproblem.hh
ewoms/models/blackoil/blackoilboundaryratevector.hh
ewoms/models/blackoil/blackoilpolymermodules.hh
ewoms/models/blackoil/blackoilratevector.hh
ewoms/models/blackoil/blackoilsolventmodules.hh

This makes it possible to set non-trivial boundary conditions in the blackoil model
Currently the boundary must be set explicit in boundary() in the eclproblem class 
and enableBoundaryMassFlux needs to be set to true in eclfluxmodule.hh
TODO
Make it settable from deck using customized keywords 
Note:
Currently it doesn't allow for polymer or solvent influx
on the boundary with the free flow option

Fix generic boundary conditions for blackoil model

---

CMakeLists.txt

In order to re-enable it we should:
- Use input and reference data in opm-tests.
- Ensure that the jenkins update feature updates it.
I'll self-merge when green, unless someone beats me to it.

Temporarily disable the SPE1 test.

---

ebos/eclequilinitializer.hh
ebos/eclfluxmodule.hh
ebos/eclproblem.hh
ewoms/disc/common/fvbaseboundarycontext.hh
ewoms/disc/common/fvbaselocalresidual.hh

The OPM specific keywords FREEBC[XYZ[-]] can be used to specify
boundary cells that are open. Default is a closed boundary.
Depends on OPM/opm-common#641

Add support for using free boundary conditions in Flow

---

ebos/eclbasevanguard.hh

**This should not be merged, but will be used internally in *Equinor*.**
The net effect of this pr is to add the option: `--enable-opm-rst-file=false` to the `flow` command line.

[Equinor internal]: Opm rst default false

---

ebos/eclproblem.hh
ewoms/common/parametersystem.hh
ewoms/common/start.hh

this hopefully makes the purpose of `ebos` crystal clear in its description. this should be interpreted as "if you use ebos in production, you are on your own and you should only expect a very limited amount of support (or even sympathy) if something breaks".

ebos: clarify startup message

---

ebos/eclproblem.hh
ebos/eclwriter.hh

Some time loop stuff was missing in the doobly-doo.
Also, I noticed that using the current version of `opm-common` it seems to be impossible do ECL restarts using a different directory for the restart files than the one which contains the `.DATA` file. is this correct @joakim-hove? if no, how can I specify the directory for `UNRST` files for `opm-common`? If yes, this functionality should IMO be added or else the `--output-dir` parameter is meaningless for restarts if the input data is not copied to that directory before restart.

ebos: Fix restart from ECL files

---

ebos/eclproblem.hh

with the merge of #480,  a semicolon went MIA. This is trivial and it fixes the build, so I self-merge immediately.

fix missing semicolon

---

ebos/ebos.cc
ebos/eclproblem.hh
ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaseproperties.hh

this is a compile time switch with the intention to be able to more easily turn experimental features that are not yet considered to be production quality on and off. DUNE has a similar mechanism (i.e., the `DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS` macro), but this relies on the preprocessor.
For now, the property does not have any effect.

introduce an "experimental mode"

---

ebos/eclproblem.hh

Usage
BCRATE
1 1 1 1 1 10 X WATER 1e-7 /
This will inject 1e-7 of water (mass/time/length/length) on the x side of the
boundary cells with cartesian index [1 1 1] to [1 1 10]
Depends on OPM/opm-common#648

Add option for setting mass boundary rate from deck

---

ewoms/linear/istlsparsematrixadapter.hh

this method seems to be intended only for BCRS matrices which are build in implicit mode. This might be a mistake in DUNE because the method works fine for any matrices provided that they are fully set up.
This assert is only triggered if the `DUNE_ISTL_WITH_CHECKING` macro is set, so the impacts of this mistake should be quite limited.

do not use BCRSMatrix::entry()

---

ewoms/common/simulator.hh

`flow` is unaffected by this, because it uses its own main loop.

simulator: properly handle exceptions in the pre and postprocessing routines in parallel runs

---

ewoms/models/blackoil/blackoilnewtonmethod.hh

i.e., we now check for `enable$BLACKOIL_EXTENSION` compile time variables. this should allow the compiler to produce slightly better optimized machine code if the respective extension is disabled.

black oil newton method: allow the compiler to see at compile time if  a given extension is enabled

---

ewoms/disc/common/fvbasefdlocallinearizer.hh
ewoms/io/vtkmultiphasemodule.hh
ewoms/linear/parallelamgbackend.hh
ewoms/linear/parallelistlbackend.hh

this is part of the pre-release maintainance: all eWoms headers should now be includable without strings attached, i.e., in any order and without having to include something before.

make all headers self sufficient

---

ewoms/common/simulator.hh

`timeStepSize()` now always returns the value specified via `setTimeStepSize()`, i.e., the time loop is now solely responsible for not crossing episode boundaries in the middle of time steps and for not going past the specified end time of the simulation.

simulator: simplify the time step handling a bit

---

ewoms/io/vtkblackoilmodule.hh
ewoms/models/blackoil/blackoilintensivequantities.hh

the oil saturation for the current iteration can be larger than the historic maximum. since oil saturation typically goes down over time in oil reservoirs, the impact of this is likely very limited...
this PR depends on OPM/opm-material#332 (but the inverse is not the case)

black oil: fix the determination of the maximum oil saturation

---

ewoms/common/simulator.hh

currently, the practical implications of this are very limited...

pass the correct value for the isSubstep parameter of problem_->writeOutput()

---

ewoms/common/simulator.hh
ewoms/disc/common/fvbaseproblem.hh

with the recent fixes to `flow`, this is equivalent to `!simulator.episodeWillBeOver()`.

remove the isSubstep parameter from Problem::writeOutput()

---

ewoms/disc/common/fvbasediscretization.hh
ewoms/linear/parallelbasebackend.hh

so far, this property was specified by the level of the base discretization. because explicitly set properties overwrite the stuff inherited from splices, so far it was not possible to specify linear solver backends which require a custom sparse matrix adapter unless the sparse matrix adapter class was explicitly set again at the problem level -- thus making the splice much less generic than it ought to be. (also, the whole point of the sparse matrix adapter abstraction is that the discretization does not need to know what the sparse matrix code does internally.)

let the linear solver backend determine the type of the sparse matrix adapter

---

ewoms/disc/common/fvbaseprimaryvariables.hh
ewoms/models/blackoil/blackoilpolymermodules.hh
ewoms/models/common/energymodule.hh
ewoms/models/pvs/pvsprimaryvariables.hh

with OPM/opm-material#340, this will throw an exception. Never try to fix more than one thing at once...
Right now, this PR can be merged as-is as it is, and it is IMO a good idea to do so, because it is IMO good style to not to give the impression that a plain floating point object can represent an AD variable. It is required before for OPM/opm-material#340 can go in.

do no longer call createVariable() for plain floating point types

---

CMakeLists.txt
ewoms/disc/common/fvbaseboundarycontext.hh
ewoms/disc/common/fvbaseelementcontext.hh
ewoms/disc/common/fvbasegradientcalculator.hh
tests/lens_immiscible_ecfv_ad_23.cc

In Element context global position definition sometimes the Grid::dimension is used instead of Grid::dimensionworld. This leads to compile errors when dimension != dimensionworld.

Fix mixup between Grid::dimension and Grid::dimensionworld

---

ewoms/common/parametersystem.hh

this might be wanted in some instances.

parameter system: allow to specify empty strings

---

ewoms/common/simulator.hh

for some reason, this happens with SPE-10 model 2.

simulator: make episode{Is,WillBe}Over() work if startTime() is negative

---

ewoms/disc/common/fvbaseproblem.hh
ewoms/nonlinear/newtonmethod.hh

the time integration code now tries to update once with exactly the minumum time step size before bailing out, the error message when aborting the run because of encountering a time step size smaller than the minimum now makes sense, and the parameters for the time integration are not fixed anymore but queried from the implementation of the problem, i.e., they can change over the course of the simulation.

improve and generalize the time integration

---

bin/runtest.sh
ewoms/common/parametersystem.hh
ewoms/common/start.hh

This patch is part of the quest to reduce surprising/unexpected behaviors and it aborts the simulation with a hopefully useful error message if unknown parameters are specified at runtime. The implementation of this is general, i.e. it works for any simulators that use `Ewoms::start()` without any scaffolding around it: with no modifications to opm-simulators `mebos` will give up if it encounters a parameter that is unknown to the black-oil variant and it will print the usage message multiple times on `--help`. `flow` will work as before but it will start complaining about unknown parameters. OPM/opm-simulators#1916 rectifies these issues.

Ewoms::start(): abort the run when encountering unknown parameters

---

ewoms/common/parametersystem.hh

meaningless and causes warnings.

remove const qualifier on return value

---

ewoms/disc/common/fvbasediscretization.hh
ewoms/disc/common/fvbaseproblem.hh
ewoms/disc/common/fvbaseproperties.hh

this is basically a continuation of #522. By itself, this PR does nothing if `--continue-on-convergence-error=true` is not explicitly specified on the command line.

implement option to continue if time integration failed with minimum time step

---

ewoms/linear/globalindices.hh
ewoms/linear/overlappingbcrsmatrix.hh

missed originally as they are only emitted from clang, not gcc

changed: quell some more unused parameter warnings without MPI

---

ewoms/models/blackoil/blackoilboundaryratevector.hh
ewoms/models/blackoil/blackoilfoammodules.hh
ewoms/models/blackoil/blackoilindices.hh
ewoms/models/blackoil/blackoilintensivequantities.hh
ewoms/models/blackoil/blackoillocalresidual.hh
ewoms/models/blackoil/blackoilmodel.hh
ewoms/models/blackoil/blackoilnewtonmethod.hh
ewoms/models/blackoil/blackoilprimaryvariables.hh
ewoms/models/blackoil/blackoilproperties.hh
ewoms/models/blackoil/blackoilratevector.hh
ewoms/models/blackoil/blackoiltwophaseindices.hh

This adds a foam module, which should be considered experimental for the time being. It supports a subset of foam features: most importantly gas mobility reduction tables (FOAMMOB) and foam adsorption (FOAMADS, FOAMROCK).
A companion PR in opm-simulators is needed.

Add foam module

---

opm/simulators/linalg/overlappingscalarproduct.hh

Scalarproduct::norm and Scalarproduct::dot are const in those
versions and these changes are not backwards compatible.

Adapt to constification of Scalarproduct for 2.7.0 or newer.

---

opm/models/blackoil/blackoilfoammodules.hh

shut up clang, please shut up!

quell some unused parameter warnings

---

opm/models/utils/simulator.hh

This broke all tests in opm-models.

fixed: do not assert for positive timestep when simulation is finished

---

tests/test_quadrature.cc

Fixed the following compile error in the tests for ALUGrid master. Tested with DUNE 2.4-2.7
```
/home/mblatt/src/dune/opm-release-master/opm-models/tests/test_quadrature.cc: In function ‘void testTetrahedron()’:
/home/mblatt/src/dune/opm-release-master/opm-models/tests/test_quadrature.cc:191:32: error: unable to deduce ‘auto*’ from ‘Dune::ALU3dGridFactory< <template-parameter-1-1> >::createGrid() [with ALUGrid = Dune::ALUGrid<3, 3, (Dune::ALUGridElementType)0, (Dune::ALUGridRefinementType)1>; Dune::ALU3dGridFactory< <template-parameter-1-1> >::GridPtrType = Dune::ToUniquePtr<Dune::ALUGrid<3, 3, (Dune::ALUGridElementType)0, (Dune::ALUGridRefinementType)1> >]()’
auto *grid = gf.createGrid();
^
/home/mblatt/src/dune/opm-release-master/opm-models/tests/test_quadrature.cc:191:32: note: …
```

Fixes g++-8's problems with return type deduction (ALUGrid master).

---

tests/test_quadrature.cc

Fixes the following compile error in the tests for ALUGrid master.
Tested with DUNE 2.4-2.7
```
/home/mblatt/src/dune/opm-release-master/opm-models/tests/test_quadrature.cc: In function ‘void testTetrahedron()’:
/home/mblatt/src/dune/opm-release-master/opm-models/tests/test_quadrature.cc:191:32: error: unable to deduce ‘auto*’ from ‘Dune::ALU3dGridFactory< <template-parameter-1-1> >::createGrid() [with ALUGrid = Dune::ALUGrid<3, 3, (Dune::ALUGridElementType)0, (Dune::ALUGridRefinementType)1>; Dune::ALU3dGridFactory< <template-parameter-1-1> >::GridPtrType = Dune::ToUniquePtr<Dune::ALUGrid<3, 3, (Dune::ALUGridElementType)0, (Dune::ALUGridRefinementType)1> >]()’
auto *grid = gf.createGrid();
^
/home/mblatt/src/dune/opm-release-master/opm-models/tests/test_quadrature.cc:191:32: note: …
```

Fixes g++-8's problems with return type deduction (ALUGrid master). (backport #570)

---

opm/models/blackoil/blackoilonephaseindices.hh
opm/simulators/linalg/combinedcriterion.hh
opm/simulators/linalg/convergencecriterion.hh
opm/simulators/linalg/fixpointcriterion.hh
opm/simulators/linalg/istlpreconditionerwrappers.hh
opm/simulators/linalg/istlsolverwrappers.hh
opm/simulators/linalg/istlsparsematrixadapter.hh
opm/simulators/linalg/linearsolverreport.hh
opm/simulators/linalg/parallelbasebackend.hh
opm/simulators/linalg/parallelbicgstabbackend.hh
opm/simulators/linalg/parallelistlbackend.hh
opm/simulators/linalg/residreductioncriterion.hh
opm/simulators/linalg/weightedresidreductioncriterion.hh

to make it consistent with the rest. #530 development must have been started before the renaming in #532 and somehow the old namespace survived.
Downstream PR is coming.

Move BlackOilOnePhaseIndices to Opm namespace

---

opm/models/blackoil/blackoilsolventmodules.hh

While working on refactoring defaults - to refactor the 3D system I encountered this problem. There is bug/feature in the `DeckItem::getData()` function which is easy to get fooled by. The opm-common Deck data structures try quite hard to keep control over what data is assigned/defautled/and... and so on - but by using:
```
std::vector<T> data& = deck_item::getData<T>(0);
```
you can bypass virtually all checks and get invalid data[1]. When things were refactor the code addressed in this PR produced undefined values.
This PR can (and should!) be merged right away - indepent of the ongoing efforts in opm-common; but it must be merged before/along with https://github.com/OPM/opm-common/pull/1230.
[1]: This is being tightened up.

Use DeckItem::hasValue() before accessing Todd Langstaff parameters

---

opm/models/blackoil/blackoilfoammodules.hh
opm/models/blackoil/blackoilpolymermodules.hh
opm/models/blackoil/blackoilsolventmodules.hh

Admittedly this is a little motivated by lazyness;
I need acesss to the data members in these singletons so I can serialize for parallelization purposes. Writing the (non-)mutable acessors for all these variables seems like a lot of noise for very little gain.

Add serialization templates

---

CMakeLists.txt
CMakeLists_files.cmake
bin/runtest.sh
opm/models/parallel/mpiutil.hh
opm/models/utils/simulator.hh
tests/test_mpiutil.cc

Ensures user sees any useful exception messages during initialization. This scratches an old itch, probably not just for me, but also for frustrated users.
As of now, for certain types of failure that for example throw during fluid system construction or equilibration, the user only sees a generic "Could not initialize the problem" message. The .DBG file also just gets the same message.
With the proposed code, we gather the error strings (if any) from each process, and print the first one. This should be appropriate, as usually all processes throw for the same reason in this phase. If not, printing the first should let the user fix the problem (in the deck usually) and try again, eventually seeing all problems.
To implement this, I basically imported and refactored a bit of code from …

Add and use gatherStrings() for exception messages.

---

CMakeLists.txt

Downstream of https://github.com/OPM/opm-common/pull/1492

disable building of test if Boost::test is not found

---

opm/models/io/cubegridvanguard.hh
opm/models/io/simplexvanguard.hh

Those methods return a unique_ptr since at least DUNE 2.6.
Probably I am having weired options such that these code paths even get compiled.

Fix compilation issues due to removed Dune::shared_ptr.

---

opm/models/parallel/gridcommhandles.hh

This fixes an occuring segfault caused by incorrect interface method overload. It occurs with recent DUNE 2.7 (including backport) or later versions. This must go into the release.

[bugfix][GridCommHandle] fix incorrect signature of overloaded interface method.

---

opm/models/blackoil/blackoilnewtonmethod.hh
opm/models/blackoil/blackoilprimaryvariables.hh

New pullrequest for introducing the possibility of saturation chopping. This should not modify the solution with default setting. To be able to do this it is slightly unlogical for surfactant runs.

Pure saturation chopping

---

opm/models/blackoil/blackoilprimaryvariables.hh

Fixes a self-assignment issue.

Properly Scale Solvent Saturation

---

opm/models/utils/parametersystem.hh

anonoymize unused parameter

---

tests/problems/fractureproblem.hh

The layout parameter has been deprecated some time ago and now removed
in DUNE > 2.7. This commit fixes its last usage in opm-models makes it
compiler with DUNE master.

Use correct number of template arguments for fracture problem DUNE>2.7

---

opm/models/common/darcyfluxmodule.hh

The darcyfluxmodule had a  sign mistake and a missing division by distance in the calculation of the contribution of gravity to the flux on boundaries. The fix is consistent with the implementation of the gravity on internal faces (in calculateGradients_(...) )

Fixed bug in calculation of gravity contribution to boundary flux

---

opm/models/utils/parametersystem.hh

Requested by some developers to more easily see the full set of hidden options.

Add --help-all option that also prints hidden options.

---

opm/models/utils/propertysystem.hh

Still available by manually overriding OPM_ENABLE_OLD_PROPERTY_MACROS, but not by default. This change has been communicated for a long time, as due to happen after the 2020.10 release.
Do not backport to the release.

Disable property macros.

---

opm/models/blackoil/blackoilextbomodules.hh

The two types may be the same, in which case this is a build failure.
We switch to using templates for the property evaluation functions to allow the compiler to specialise it for all pertinent types.  In so doing we also need to explicitly form an `Evaluation` instance that was only implicitly constructed before.

ExtBoModule: Don't Overload on Scalar and Evaluation

---

opm/models/blackoil/blackoilboundaryratevector.hh
opm/models/blackoil/blackoilratevector.hh

Add guard against unused phases and mapping to active index. 
Again many thanks to valgrind.

Fix 2-phase blackoil boundary

---

opm/models/discretization/common/fvbaseboundarycontext.hh
opm/models/discretization/common/fvbaselocalresidual.hh

The process boundaries are included in the vector of boundary intersections in the stencil i.e. numBoundaryFaces both includes number of real boundaries and process boundaries. This fix make sure that the iterator and the faceIdx are consistent.

fix boundary face index in parallel

---

CMakeLists_files.cmake
opm/models/blackoil/blackoildiffusionmodule.hh
opm/models/blackoil/blackoilextensivequantities.hh
opm/models/blackoil/blackoilintensivequantities.hh
opm/models/blackoil/blackoillocalresidual.hh
opm/models/blackoil/blackoilmodel.hh
opm/models/common/diffusionmodule.hh

Diffusion must be enabled compile time i.e. this should not affect the standard flow at all. 
Before enabling diffusion as default its accuracy and potential performance penalty needs to be investigated. 
Depends on OPM/opm-material#443

Add blackoil diffusion module

---

opm/models/discretization/common/fvbaselocalresidual.hh

Should fix test failure in opm-models. 
Solution suggested by @blattms

move the boundary check downstream

---

opm/models/blackoil/blackoilratevector.hh

since it already has an assigment operator, the implicit
copy-constructor is deprecated. clang likes to
point this out.

Remove explicit assignment-operator from class

---

opm/models/blackoil/blackoilextbomodules.hh

Adding some more explicit extrapolation to avoid hard-crash when values are out of range.

Extrapolate pvt properties in the extended blackoil model

---

opm/models/discretization/common/fvbaseelementcontext.hh

This seems to yield a consistent speedup of assembly in my tests.

Don't copy primary variables into element context

---

opm/models/blackoil/blackoilbrinemodules.hh
opm/models/blackoil/blackoilintensivequantities.hh
opm/models/blackoil/blackoillocalresidual.hh
opm/models/blackoil/blackoilnewtonmethod.hh
opm/models/blackoil/blackoilprimaryvariables.hh

Main items
1) adding gas-water ratio (Rvw)  to the black-oil equations
2) variable switching Sw<->Rvw ( typically water may disappear due to evaporation)
3) flux correction in case of mobility reduction  due to salt precipitation  (opm/models/blackoil/blackoilbrinemodules.hh)
This PR depends on https://github.com/OPM/opm-material/pull/491

Enabling water evaporation into the gas phase

---

opm/models/blackoil/blackoilnewtonmethod.hh

It seems like currentValue.primaryVarsMeaningBrine() will return an uninitialized variable if enableSaltPrecipitation is false. This can lead to undefined behavior especially in a parallel run. Hence we also check whether salt precipitation is is enabled and do nothing otherwise.
Backport of #690 to release

[backport,bugfix] Prevent accessing undefined variables for brine.

---

opm/models/blackoil/blackoildiffusionmodule.hh

fixed: avoid copying int quants for diffusion

---

opm/models/discretization/common/fvbasediscretization.hh

writes to `vector<bool>` is not thread safe.
closes https://github.com/OPM/opm-simulators/issues/3993

fixed: avoid vector<bool> in fvbasediscretization

---

opm/models/discretization/common/fvbasediscretization.hh
opm/simulators/linalg/matrixblock.hh

Reverts OPM/opm-models#708
For whatever reason, the Norne model does not run with this change.

Revert "changed: unify matrixblock.hh with downstream MatrixBlock.hpp"

---

opm/models/blackoil/blackoillocalresidualtpfa.hh

No test currently exercise this, that will change when eventually OPM/opm-simulators#4017 gets merged.

Bugfix: make TPFA version of local linearizer work for two-phase runs.

---

opm/models/discretization/common/fvbasediscretization.hh
opm/simulators/linalg/matrixblock.hh

Let's try this again.
The issue was that previously a generic utility function was returning the identity matrix for a failed invert.
I changed this and did not realize something was relying on this rather funky behavior (ie the Norne model).
I have now changed it so the generic utility throws, and then the exceptional behavior is applied locally in the well
code instead.
If you do not like this approach and rather want the old one I can do that, but I really do not think that is the proper way to do it.

changed: unify matrixblock.hh with downstream MatrixBlock.hpp

---

opm/models/discretization/common/fvbaseintensivequantities.hh

is no need to explicitly declare the cc here

fixed: respect rule-of-three for fvbaseintensivequantities

---

opm/models/blackoil/blackoilbrinemodules.hh
opm/models/blackoil/blackoilnewtonmethod.hh

@plgbrts  It should use the current porosity before being modified by salt precipitation in `blackoilintensivequantities.hh`, i.e., $\phi/(1-S_p)$?

Bug fix on solid salt calculation

---

CMakeLists_files.cmake
opm/models/blackoil/blackoilmicpmodules.hh
opm/models/blackoil/blackoilmicpparams.hh
opm/models/blackoil/blackoilnewtonmethod.hh

limits the amount of static variable declarations
also clean up variable names.

blackoilmicpmodules: put parameters in separate class

---

opm/models/blackoil/blackoilmodel.hh

Changed definition to avoid getting them from TypeTag.
The current use is analytic cpr weights.

made definition of model fluid,indices and primaryvariables public

---

opm/models/blackoil/blackoilintensivequantities.hh
opm/models/blackoil/blackoillocalresidualtpfa.hh
opm/models/common/multiphasebaseproblem.hh
opm/models/discretization/common/tpfalinearizer.hh
opm/models/discretization/ecfv/ecfvstencil.hh

Depends on https://github.com/OPM/opm-material/pull/532 and https://github.com/OPM/opm-common/pull/3113

Add support for directional relative permeabilities

---

CMakeLists_files.cmake
opm/models/blackoil/blackoilintensivequantities.hh
opm/models/common/directionalmobility.hh
opm/models/common/multiphasebaseproblem.hh

Background: This PR is trying to fix the build test problem in https://github.com/OPM/opm-models/pull/714 that was discovered after it was merged into master.
Moves the `updateRelperms()` method in `BlackOilIntensiveQuantities` to the `xxxProblem` class. This is a more natural place for this method and it avoids including `EclMaterialManager` into the `BlackOilIntensiveQuantities`. The `DirectionalMobility` struct is moved to a separate file such that it can be included from both the `xxxProblem` files and the `BlackOilIntensiveQuantities`.
See also the companion PR https://github.com/OPM/opm-simulators/pull/4132 in opm-simulators.

Move updateRelperms() to the problem class

---

opm/models/common/multiphasebaseproblem.hh

That way we won't get compiler warnings about unused parameters.

Tag 'updateRelperms' Parameters as Maybe Unused

---

opm/models/blackoil/blackoilnewtonmethod.hh

This removes the default temperature clamping limits for the blackoil thermal model.

change default max/min temp in newton clamping

---

opm/models/blackoil/blackoilmodel.hh

No reason to treat the diffusion parameters differently. This caused the FlowEarlyBird (TypeTag) set of parameters to differ from the one used for Flow blackoil, since that (using TpfaLinearizer) does not activate diffusion.
Closes OPM/opm-common#3168

Register all (not just some) of the vtk parameters unconditionally.

---

opm/models/discretization/common/fvbaseproblem.hh

For OPM Flow, this only affects VTK output.

Use current dir for output by default.

---

opm/models/discretization/common/fvbasediscretization.hh
opm/models/discretization/common/fvbaseproblem.hh
opm/models/io/vtkmultiwriter.hh
opm/models/nonlinear/newtonmethod.hh
opm/models/utils/simulator.hh
opm/simulators/linalg/overlappingscalarproduct.hh

Compilation of the tests has broken since month for DUNE 2.6.
Somewhat related to OPM/opm-grid#587, but should also be mergable independently.

Fixes compilation with DUNE 2.9 and 2.6

---

opm/models/nonlinear/newtonmethod.hh

removing function details::getMPIHelperCommunicator() in newtonmethod.hh
This backports #742

using Dune::MPIHelper::getCommunicator() in newtonmethod.hh

---

opm/models/discretization/common/fvbaselinearizer.hh
opm/models/discretization/common/tpfalinearizer.hh

Implement for the TpfaLinearizer to update transmissibilities. The regular linearizer stores no such parameters and has an empty implementations.
Necessary to handle correctly cases with e.g. MULTFLT in the SCHEDULE section. Downstream PR adds call to this method.

Add interface for updating stored parameters in linearizers.

---

CMakeLists_files.cmake
opm/models/nonlinear/newtonmethod.hh
opm/models/nonlinear/newtonmethodproperties.hh

Now they can be reused in opm-simulators without any hassle.
There will be a downstream change.

Put properties of Newton method into separate header for reuse.

---

opm/models/blackoil/blackoilboundaryratevector.hh

Since this is a bug fix I add a release flag. 
Case with free boundary on the right and an injector injecting 10 C on the left. 
Current master
With PR

fix bug in boundary conditions for energy by adding the scaling factor

---

opm/models/blackoil/blackoilbrinemodules.hh
opm/models/blackoil/blackoilextbomodules.hh
opm/models/blackoil/blackoilindices.hh
opm/models/blackoil/blackoilintensivequantities.hh
opm/models/blackoil/blackoilmodel.hh
opm/models/blackoil/blackoilnewtonmethod.hh
opm/models/blackoil/blackoilonephaseindices.hh
opm/models/blackoil/blackoilprimaryvariables.hh
opm/models/blackoil/blackoilsolventmodules.hh
opm/models/blackoil/blackoiltwophaseindices.hh
opm/models/io/vtkblackoilmodule.hh

The primary variable meaning enums are split into three waterMeaning, gasMeaning and pressureMeaning to allow for all combination of the variables. This simplify the code and logic it also make it easier to add more switching options.

Refactor primary variable meaning

---

opm/models/discretization/common/tpfalinearizer.hh

A bug was triggered by a case placing MULTFLT at the start of the SCHEDULE. Then the required structures would be empty and the simulator bombed. With the change, we increase robustness and address this.

Allow updateStoredTransmissibilities() before createMatrix_().

---

opm/models/discretization/common/tpfalinearizer.hh
opm/simulators/linalg/istlsparsematrixadapter.hh

Add direct access to matrix elements in tpfalinearizer. Seems to give a speedup of 10% for this part. off assembly. Together with not using local well assembly more speedup is seen.
Edit: By direct access to matrix elements, we mean that instead of using `m[row][col]` to access the matrix block to be modified (via the `addToBlock(row, col)` call), we store pointers to the relevant block. The `m[row][col]` requires a search on the relevant row to find the correct block matching the requested column number.

Matrix direct access

---

opm/models/blackoil/blackoildiffusionmodule.hh
opm/models/blackoil/blackoilintensivequantities.hh
opm/models/blackoil/blackoillocalresidual.hh
opm/models/blackoil/blackoillocalresidualtpfa.hh
opm/models/blackoil/blackoilmodel.hh
opm/models/blackoil/blackoilnewtonmethod.hh
opm/models/blackoil/blackoilprimaryvariables.hh
opm/models/blackoil/blackoilproperties.hh

With GASINWAT enabled gas in allowed to dissolved into water. 
Mutual dissolution in water and oil is not supported. 
The idea there is to provide a function/table that map rs -> rsw

Support dissolved gas in water

---

opm/models/blackoil/blackoillocalresidualtpfa.hh
opm/models/discretization/common/fvbasediscretization.hh
opm/models/discretization/common/tpfalinearizer.hh

The existing code adds the source terms cell by cell, and when a perforated cell is reached, all wells and perforations are iterated over to find the correct term to add. So with K total perforations, we do O(K^2) work. with the current PR, the well source terms will be treated separately, iterating over all wells and perforations just once, so O(K) work.
The difference for the assembly performance is modest: ~3% improvement observed (with SPE9, which has a fairly high number of wells for its size). But we see that there are more parts here that can be improved, building on this. We think similarly changing the approach for aquifers may give a similar boost for example.
We add a command line option `--separate-sparse-source-terms` to control the new feature (default is true, activating …

Add well source terms to the residual separately.

---

opm/models/blackoil/blackoilprimaryvariables.hh

The only-water special case only make sense for 3p cases where it is used to avoid singular matrices not of 2p gas-water case.

fix gaswater case with only water

---

opm/models/discretization/common/fvbaseelementcontext.hh
opm/models/discretization/ecfv/ecfvstencil.hh
opm/models/parallel/threadedentityiterator.hh

These changes were made in a different branch (#682) but have been extracted to a separate PR as they are independent of the other changes in that branch.

Avoid copying data for minor speed improvement

---

opm/models/blackoil/blackoilnewtonmethod.hh
opm/models/discretization/common/fvbasediscretization.hh
opm/models/discretization/common/fvbaselinearizer.hh
opm/models/discretization/common/tpfalinearizer.hh

Added to have a place for discussion, as for its downstream PR OPM/opm-simulators#3764.

Linearization support for nonlinear domain decomposition methods

---

.clang-format

removing a warning when using an IDE.
same with https://github.com/OPM/opm-common/pull/3616 and will self-merge.

removing the duplicated AlignAfterOpenBracket entries in .clang-format

---

opm/models/blackoil/blackoilnewtonmethod.hh
opm/models/discretization/common/tpfalinearizer.hh

This fix is necessary for using the NLDD method in MPI parallel runs. There are also fixes coming in opm-simulators but they are independent of this so it can be considered separately.
We must avoid collective operations (here: doing comm.sum() to detect exceptions on any process) in single-domain contexts, as those will not be synchronous across processes (similar to the situation for single-well contexts). Moving the logic to a different function preserves existing behaviour for regular Newton.

Avoid collective operations in single-domain calls.

---

opm/models/blackoil/blackoilprimaryvariables.hh

This bug could lead to oscillation between primary variables for non constant temperature cases.

Use temperature from depth in primaryvariable switching

---

opm/models/flash/flashratevector.hh

it does not look like used.
removing it will make the class more generic in some way.

removing NCPFlash header file in flashratevector

---

opm/models/flash/flashboundaryratevector.hh
opm/models/flash/flashextensivequantities.hh
opm/models/flash/flashindices.hh
opm/models/flash/flashlocalresidual.hh
opm/models/flash/flashprimaryvariables.hh

it does not looks like it is used.
At least, [flashboundaryratevector.hh](https://github.com/OPM/opm-models/compare/master...GitPaean:removing_flashproperties?expand=1#diff-46406dee878bf82a0f5e5ec542173608fc1c30fc7cd6a25c7e486b6c645601fd)  can reused by other flash solvers directly after removing this header files.  Others might need some adjustments before it can reused directly. 
There might be some design here, but they can be added back anytime when needed.  At least, with its current form, they are NOT used in anyway.

removing flashproperties.hh from multiple files

---

opm/models/io/vtkblackoilenergymodule.hh

If the flag `--enable-vtk-output=true` is added to cases with `THERMAL` on the RUNSPEC section (e.g., [CO2STORE_ENERGY.DATA](https://github.com/OPM/opm-tests/blob/master/co2store/CO2STORE_ENERGY.DATA)), then the simulation throws 
```
Report step  0/2 at day 0/18250, date = 01-Jan-2025
Writing visualization results for the current time step.
Assertion failed: (phaseIsActive(phaseIdx)), function canonicalToActivePhaseIdx, file BlackOilFluidSystem.cpp, line 372.
```
This commit fixes this.

Fix to write VTKS when THERMAL is on deck

---

opm/models/blackoil/blackoilfoamparams.hh

compilation error is about missing type Opm::Phase

Included missing header causing compile errors with gcc-13

---

dune.module

We do use a lot of headers from it and opm-grid (which also pulls it in) is optional.

Depend on opm-common as a DUNE module

---

opm/models/blackoil/blackoillocalresidualtpfa.hh
opm/models/discretization/common/tpfalinearizer.hh

This fixes issue when using BCPROP with type FREE and DIRICHLET in a 2p run.

Fix BC Free for 2p problems

---

opm/models/parallel/mpibuffer.hh

According to MPI standard the ERROR field of MPI_Status might not be initialized unless for operations that return multiple statuses, see  Section 3.7.5 of the standard. In older OpenMPI versions (<=4.0.x) we were lucky that ERROR was initialized to 0 always. This is not the case for 4.1.y at least. See open-mpi/ompi#12049.
Therefore we skip the additional manual that has no effect with the default error handler and rely on the error handler aborting the program.
Fixed running the tests on Debian bookworm

[fix] Skip manual error checking and rely on the error default handler aborting

---

opm/models/blackoil/blackoilenergymodules.hh

We don't need these on functions.

Remove Closing Brace Semicolon

---

opm/models/blackoil/blackoillocalresidualtpfa.hh
opm/models/discretization/common/tpfalinearizer.hh

In the current code BCPROP is ignored if it is not set in the first time step. This PR make it possible to set BCPROP later in the schedule.

fix issue when BCPROP is not set initially

---

opm/models/blackoil/blackoilbrinemodules.hh
opm/models/blackoil/blackoilbrineparams.hh
opm/models/blackoil/blackoilintensivequantities.hh
opm/models/blackoil/blackoilprimaryvariables.hh
opm/models/blackoil/blackoilproblem.hh

With https://github.com/OPM/opm-common/pull/3857, this PR adds support for dynamically scaling the capillary pressure as a result of porosity changes in salt precipitation. This is achieved by adding a multiplier using tables, as it is done for the permeability reduction (while the pcfact tables are set for each satnum region, the current implementation of permfact is defined via the pvtnum regions; this PR could changed that to satnum as well if it is of interest). An example of this functionality can be found in https://github.com/OPM/opm-tests/pull/1117. The Figure on the left corresponds to the resulting PC surface for that example and on the right the comparison for the salt precipitation in the bottom cell with and without this feature.

Support for dynamic scaling of capillary pressure due to salt precipitation

---

opm/models/blackoil/blackoilenergymodules.hh

For numerical aquifers the thermal half transmissibiltes are zero which results in infinite update. We may think about adding the option for setting these from deck. As a first approach we fix the code to allow for zero values.

avoid divition by zero for case without conductivity

---

opm/simulators/linalg/parallelamgbackend.hh

The function 'setUseFixedOrder' is called if it is defined and the matrices in the AMG hierarchy are constructed with deterministic indices. If its not defined yet, it is not called and the matrices in the AMG hierarchy are constructed with non-deterministic indices.

Construct the matrices in the AMG hierarchy with deterministic indices if possible.

---

opm/models/discretization/common/tpfalinearizer.hh

If we would try that then we would index vectors with index -1 and possibly overwrite other system information. This was the case for some models resulting in cryptic errror " corrupted size vs. prev_size"
Now we simply do nothing for NNCs.

[bugfix] Do not try to save FLOWS or FLOWRES values for NNCs.

---

opm/models/discretization/common/tpfalinearizer.hh

Restores NNC output for Flows. 
See #873

Fix Flows/Flores for NNCs

---

opm/models/blackoil/blackoillocalresidualtpfa.hh
opm/models/blackoil/blackoilprimaryvariables.hh

These parameters get referenced only in certain configurations.

Tag Certain Parameters As Maybe-Unused

---

opm/models/blackoil/blackoildiffusionmodule.hh
opm/models/common/diffusionmodule.hh

they used to use the same EWOMS_DIFFUSION_MODULE_HH
It looks like `#pragma once` might be better when coming to this.

changing including guard name for two diffusionmodule

---

opm/models/utils/parametersystem.hh

This macro is unused, it adds no convenience in any case and less macros is always good.

Remove unused EWOMS_RESET_PARAMS macro

---

opm/models/utils/parametersystem.hh

it simplifies nothing, only obscures.
remove unused different propTagName and use paramName.

remove macro EWOMS_PARAM_IS_SET macro

---

opm/models/utils/parametersystem.hh
opm/models/utils/start.hh

it adds no simplicity and only obfuscates

remove EWOMS_GET_PARAM_LISTS macro

---

opm/models/utils/parametersystem.hh

it adds no simplicity and only obfuscates

remove EWOMS_HIDE_PARAM macro

---

opm/models/discretization/common/fvbasediscretization.hh
opm/models/utils/basicproperties.hh
opm/simulators/linalg/parallelbasebackend.hh
tests/problems/co2injectionproblem.hh
tests/problems/co2ptflashproblem.hh
tests/problems/diffusionproblem.hh
tests/problems/fingerproblem.hh
tests/problems/lensproblem.hh
tests/problems/powerinjectionproblem.hh
tutorial/tutorial1problem.hh

registered as int and obtained as unsigned, or registered as Scalar and obtained as int

fixed: inconsistent parameter setups

---

opm/models/utils/parametersystem.hh

Let's get rid of the final method that is string based.

Parameters::isSet: pass parameter struct instead of stringified

---

opm/models/blackoil/blackoillocalresidualtpfa.hh
opm/models/discretization/common/tpfalinearizer.hh

Call is expensive, might also be good to improve the function in opm-common. (FaceDir.cpp) I leave that to others though.
This fixes the significant preformance regression in flux calculations that was introduced earlier. On the order of 5% total at least.

Avoid call to FaceDir::FromIntersectionIndex() in hot path.

---

opm/models/blackoil/blackoilfoammodules.hh
tests/problems/co2ptflashproblem.hh

It makes no sense to use run-time parameters as properties, it only obtains the default values, not possible runtime values.

Fix runtime parameters used as properties

---

opm/models/blackoil/blackoilprimaryvariables.hh

For the case of gas being dissolved in water, the water saturation is not initialized explicitly, such that it is currently set to the default 0.0.
This fix should not change the behaviour of `primaryVarsMeaningWater` as the water saturation is hardcoded for the RSW case in [line 768](https://github.com/OPM/opm-models/blob/81cddce56fa5630a696272f90b5ad8a240e05968/opm/models/blackoil/blackoilprimaryvariables.hh#L768)
```C++
computeCapillaryPressures_(pC, /*so=*/ 0.0,  /*sg=*/ 0.0, /*sw=*/ 1.0, matParams);
```
but it might cause issues later if someone uses sw directly. 
For  `primaryVarsMeaningGas` there might be an impact, depending on what primary variable is being used for gas.
There might be other bugs like this in the code, as it is hard to have an overview of all the different …

initialize water saturation for gas dissolved in water

---

opm/models/blackoil/blackoilindices.hh
opm/models/blackoil/blackoilonephaseindices.hh
opm/models/blackoil/blackoiltwophaseindices.hh

I am aware this is functionally equivalent, but it's nice to be explicit about the compile time availability of these values.

Use constexpr in blackoil indices classes

---

opm/models/utils/basicparameters.hh
opm/models/utils/basicproperties.hh
opm/models/utils/propertysystem.hh
opm/models/utils/start.hh

property introspection is not supported and unlikely to return.
this has not been supported since the property/typetag system was changed from the old macro based implementation, ie, for the last 5 years. since the new system is based on partial specialization of structs, this is unlikely to ever return since we'd need reflection support to implement it.

changed: remove the print-properties parameter

---

opm/models/utils/parametersystem.hh

Float version not included in current version of libc++(15).

Add workaround for libc++ incomplete from_chars().

---

CMakeLists.txt

CMAKE_SOURCE_DIR does not point to the correct directory for super build
Sorry for not picking this up during review..

fixed: use PROJECT_SOURCE_DIR

---

opm/models/blackoil/blackoillocalresidualtpfa.hh

* avoid getting zero in matrix in zero pressure/zero flux case
* may make it easier to have lower/upper limits on pressures
This should be the correct, but it will may change many tests so it should be investigated carefully.

Avoid deleting derivatives with zero pressure difference

---

opm/models/blackoil/blackoilconvectivemixingmodule.hh
opm/models/blackoil/blackoilmicpmodules.hh
opm/models/blackoil/blackoilnewtonmethod.hh
opm/models/blackoil/blackoilprimaryvariables.hh
opm/models/discretization/common/fvbasediscretization.hh
opm/models/nonlinear/newtonmethod.hh

Various small niggles to enable usage of float Scalars.

Add necessary changes to build float simulators
