OPM/opm-models

applications/ebos/eclgridmanager.hh
Followup to: https://github.com/OPM/opm-parser/pull/527
=> Use ParseMode argument.

applications/ebos/eclequilinitializer.hh, applications/ebos/eclgridmanager.hh, applications/ebos/eclproblem.hh, applications/ebos/ecltransmissibility.hh, applications/ebos/eclwellmanager.hh, ewoms/common/cartesianindexmapper.hh, tests/problems/lensgridmanager.hh
This PR changes the EclGridManager such that the CartesianIndexMapper is used. 
This way also ALUGrid could be used, e.g. for SPE1 ...
The EclWellManager is changed such that only wells are added that appear to be in the domain at hand.
=> CartesianIndexMapper.

applications/ebos/eclfluxmodule.hh, applications/ebos/eclpeacemanwell.hh, applications/ebos/ertwrappers.hh, ewoms/common/parametersystem.hh, ewoms/common/propertysystem.hh, ewoms/disc/common/fvbaselinearizer.hh, ewoms/disc/common/fvbasenewtonmethod.hh, ewoms/disc/vcfv/vcfvstencil.hh, ewoms/io/baseoutputmodule.hh, ewoms/io/restart.hh, ewoms/io/vtkscalarfunction.hh, ewoms/io/vtktensorfunction.hh, ewoms/io/vtkvectorfunction.hh, ewoms/linear/nullborderlistmanager.hh, ewoms/linear/overlappingpreconditioner.hh, ewoms/models/blackoil/blackoilintensivequantities.hh, ewoms/models/common/darcyfluxmodule.hh, ewoms/models/common/forchheimerfluxmodule.hh, ewoms/models/ncp/ncpmodel.hh, ewoms/models/pvs/pvsprimaryvariables.hh, ewoms/nonlinear/newtonmethod.hh
this needs to be merged after OPM/opm-common#55
=> use the error macros from opm-common

applications/ebos/eclequilinitializer.hh, applications/ebos/eclgridmanager.hh, applications/ebos/eclproblem.hh, applications/ebos/eclwriter.hh, ewoms/common/cartesianindexmapper.hh, ewoms/io/polyhedralgridconverter.hh, ewoms/parallel/collecttoiorank.hh
This PR fixes the EQUIL initialization for ALUGrid.
It also adds parallel output to EclWriter. This also fixes the previously existing problem when elements were reordered using an SFC approach. 
This was tested with SPE9_CP.DATA
=> Equil initialization with ALUGrid and parallel ecl output.

applications/ebos/eclproblem.hh, applications/ebos/eclwellmanager.hh, dune.module, ewoms/common/cartesianindexmapper.hh, ewoms/disc/common/fvbasediscretization.hh, ewoms/models/blackoil/blackoilintensivequantities.hh, ewoms/models/blackoil/blackoilratevector.hh
This PR fixes a couple of issues with parallelization. Now, at least SPE1 can be run in parallel. So we can finally start investigating the parallelization of the wells.
=> ebos: fix issues with parallelization

ewoms/io/vtkmultiwriter.hh
This PR make the code compile with the current dune-grid master.
=> VtkMultiWriter: make compile with current dune-grid master.

jenkins/README.md, jenkins/build-ewoms.sh, jenkins/build-pr.sh, jenkins/build.sh
This is the build scripts for this module, ref OPM/opm-common#102 and OPM/opm-parser#743
This is not really a reboot since there is no ewoms build job currently. I see no reason to keep ewoms in the dark ages of software development.
=> Jenkins (re)boot

applications/ebos/eclalugridmanager.hh, applications/ebos/eclcpgridmanager.hh, applications/ebos/eclpolyhedralgridmanager.hh, applications/ebos/eclproblem.hh, applications/ebos/eclthresholdpressure.hh, applications/ebos/ecltransmissibility.hh
Downstream: 
- OPM/opm-parser#751
- OPM/opm-material#137
- OPM/opm-core#994
- OPM/opm-simulators#644
- OPM/opm-output#14
=> Using new EclipseState API

CMakeLists.txt, debian/control, debian/ebos.install, debian/rules, redhat/ewoms.spec
- install ebos
- update debian packaging
please review and all that but do not merge until i have added the rhel packaging (opening pr early to get the installation part reviewed).
@andlaus as requested.
=> Updates for 16.04 packaging

applications/ebos/eclalugridmanager.hh, applications/ebos/eclbasegridmanager.hh, applications/ebos/eclcpgridmanager.hh, applications/ebos/eclwellmanager.hh
Using new EclipseState.getInputGrid API in Parser
See OPM/opm-parser#769
=> Using getInputGrid API from Parser

jenkins/build-ewoms.sh, jenkins/build-pr.sh, jenkins/build.sh
changes done related to downstream triggers made
it easier to build upstreams as well
depends on https://github.com/OPM/opm-common/pull/111
=> simplify jenkins build scripts a little

CMakeLists.txt
conditions always evaluated to true otherwise.
hopefully compatible with cmake 2.8 as well. jenkins will tell.
=> fixed: need to deref these variables for newer cmake

applications/ebos/eclpeacemanwell.hh, applications/ebos/eclthresholdpressure.hh, applications/ebos/eclwriter.hh, ewoms/common/start.hh, ewoms/disc/common/fvbaseadlocallinearizer.hh, ewoms/disc/common/fvbasediscretization.hh, ewoms/disc/ecfv/ecfvdiscretization.hh, ewoms/disc/vcfv/vcfvdiscretization.hh, ewoms/io/vtkblackoilmodule.hh, ewoms/io/vtkdiffusionmodule.hh, ewoms/models/blackoil/blackoillocalresidual.hh, ewoms/models/blackoil/blackoilmodel.hh, ewoms/models/common/energymodule.hh, ewoms/models/common/multiphasebasemodel.hh, ewoms/models/discretefracture/discretefracturemodel.hh, ewoms/models/flash/flashlocalresidual.hh, ewoms/models/flash/flashmodel.hh, ewoms/models/immiscible/immisciblelocalresidual.hh, ewoms/models/immiscible/immisciblemodel.hh, ewoms/models/ncp/ncplocalresidual.hh, ewoms/models/ncp/ncpmodel.hh, ewoms/models/ncp/ncpprimaryvariables.hh, ewoms/models/pvs/pvslocalresidual.hh, ewoms/models/pvs/pvsmodel.hh, ewoms/models/richards/richardslocalresidual.hh, ewoms/models/richards/richardsmodel.hh, ewoms/models/stokes/stokesboundaryratevector.hh, tests/test_blackoilfluidstate.cc
this is the ewoms part of OPM/opm-material#147. the PR must be merged in lockstep lest there be breakage...
=> Localad to densead

CMakeLists.txt, jenkins/build-ewoms.sh, jenkins/build-pr.sh, jenkins/build.sh
Depends on https://github.com/OPM/opm-common/pull/168
Note an unrelated fix for the 'check' target is included in the same PR.
=> Simplify after ert reorg

applications/ebos/eclalugridmanager.hh, applications/ebos/eclcpgridmanager.hh
See: https://github.com/OPM/opm-simulators/pull/804
=> shared_ptr<EclipseGrid> -> const EclipseGrid&

redhat/ewoms.spec
- add new dependencies
- build using devtoolset-3 on redhat6
=> update redhat packaging

debian/control, debian/rules
re-enable tests, add opm-output and zlib dependencies
=> update debian packaging

applications/ebos/collecttoiorank.hh, applications/ebos/eclbasegridmanager.hh, applications/ebos/eclcpgridmanager.hh, applications/ebos/ecldeckunits.hh, applications/ebos/eclequilinitializer.hh, applications/ebos/eclproblem.hh, applications/ebos/eclsummarywriter.hh, applications/ebos/eclthresholdpressure.hh, applications/ebos/ecltransmissibility.hh, applications/ebos/eclwellmanager.hh, applications/ebos/eclwriter.hh, applications/ebos/ertwrappers.hh
Downstream of  https://github.com/OPM/opm-parser/pull/939
=> The great shared_ptr purge

ewoms/disc/ecfv/ecfvstencil.hh
that broke because of a silly mistake I made yesterday and I did not
test it with Dune 2.3. (maybe Dune 2.3 support should be dropped soon
anyway...)
this should fix #75. once the CI systems are green, I'll thus self-merge.
=> fix build on Dune 2.3

applications/ebos/eclpolyhedralgridmanager.hh
Small fix to make ebos compile with PolyhedralGrid.
=> [bugfix] make EclPolyhedralGridManager compile.

applications/ebos/eclpeacemanwell.hh, ewoms/disc/common/fvbaseadlocallinearizer.hh
=> use accessor methods to access the value and derivatives of Evaluation objects

ebos/eclfluxmodule.hh, ebos/eclproblem.hh, ewoms/disc/common/fvbasediscretization.hh, ewoms/disc/common/fvbaselinearizer.hh, ewoms/disc/ecfv/ecfvdiscretization.hh, ewoms/disc/vcfv/vcfvdiscretization.hh
this PR contains a few minor bugfixes concerning the explicit prefetching code, the determination of the upstream and downstream cells of fluxes and a smallish cleanup concerning the entity mapper.
=> Minor fixes

ebos/ecldeckunits.hh, ebos/eclequilinitializer.hh, ebos/eclfluxmodule.hh, ebos/ecloutputblackoilmodule.hh, ebos/eclpeacemanwell.hh, ebos/eclproblem.hh, ewoms/models/blackoil/blackoilintensivequantities.hh, ewoms/models/blackoil/blackoillocalresidual.hh, ewoms/models/blackoil/blackoilprimaryvariables.hh
this is the ewoms companion PR for OPM/opm-simulators#946
=> Implement two phase blackoil

ebos/eclequilinitializer.hh, ebos/eclproblem.hh, ewoms/nonlinear/newtonmethod.hh
this contains a few minor improvements for ebos. most of them aim to make ebos more flexible if it is used in "framework mode" by external code (i.e., flow_ebos)
=> ebos: misc improvements

ebos/eclproblem.hh
Downstream of https://github.com/OPM/opm-parser/pull/981
=> Mini deck is reference, not pointer

ebos/collecttoiorank.hh, ebos/eclbasegridmanager.hh, ebos/eclequilinitializer.hh, ebos/ecltransmissibility.hh
This PR fixes some parallelization issues with ebos. Especially the equilInit needs review.
=> Fix some parallelization issues.

ebos/collecttoiorank.hh
I'm sure that the results for sequential runs will be identical, but I'm not sure if the last three hunks are semantically correct.
=> CollectDataToIoRank: don't require the elements of a dune grid to be traversed in consecutive order

ewoms/io/cubegridmanager.hh, ewoms/io/simplexgridmanager.hh, ewoms/io/structuredgridmanager.hh
this lead to test failures in debug mode.
=> fix some type mismatches between parameter registration and parameter access

ewoms/linear/solvers.hh
self-merging due to (my personal) triviality policy.
=> update stale comment and remove dead link in solvers.hh

ebos/eclequilinitializer.hh, ebos/eclproblem.hh, ebos/eclthresholdpressure.hh, tests/reservoir_ncp_vcfv.cc
and two minor issues which did not warrant a separate PR IMO.
=> some ebos improvements about SWATINIT handling

ewoms/disc/common/fvbasediscretization.hh, ewoms/models/pvs/pvsmodel.hh
this caused the water-air problem to segfault in parallel.
=> do not access possibly non-existing elements and avoid zero reference pressure in the PVS model

ebos/eclbasegridmanager.hh, ebos/ecldummygradientcalculator.hh, ebos/eclfluxmodule.hh, ebos/eclpeacemanwell.hh, ebos/eclproblem.hh, ebos/ecltransmissibility.hh, ebos/eclwellmanager.hh, ebos/eclwriter.hh, ebos/ertwrappers.hh, ewoms/common/parametersystem.hh, ewoms/disc/common/fvbasediscretization.hh, ewoms/linear/overlappingblockvector.hh
With this, ebos compiles without warnings for me (clang++).
=> Silence warnings

ewoms/models/blackoil/blackoilnewtonmethod.hh
this was a stupid error introduces by ff86969: it is a very bad idea to do global communication for each entity of the process -- first because it is slow and -- more improtantly -- it will almost certainly hang the program because the number of entities is not necessarily equal on all processes (i.e., MPI gets horribly confused and desynchronizes).
(this was done by accident, but its yet another thing to remind oneself when using MPI...)
=> blackoil: fix the newton update for the MPI case

ebos/eclequilinitializer.hh, ebos/eclthresholdpressure.hh
Only apply swatinit in the initialization if swatinit is enabled.
=> Pass enableSwatinit to the OPM initialization 

doc/handbook/designpatterns.tex, doc/handbook/models.tex, doc/handbook/tutorial1.tex
thanks to @pgdr for the suggestion.
=> handbook: replace \textit by \emph

ebos/eclequilinitializer.hh, ebos/eclproblem.hh
hopefully this makes standalone `ebos` arrive at the same initial condition as `flow_ebos` if both, SWATINIT and threshold pressures are enabled. (we need to calculate the initial condition if threshold pressures as well as SWATINIT are enabled. `ebos` and `flow_ebos` diverged after OPM/opm-core#1129.)
the proposed patch is a kludge IMO, but in the light that in my opinion, SWATINIT and threshold pressures are both physically not justified and given the fact that SWATINIT must not be considered for
the threshold pressures should be considered to be a bug of the reference simulator, I think the patch is okay.
I ran "model 2" on `flow_ebos` with this and the results and performance are identical.
=> ebos: fix the interactions between SWATINIT and threshold pressures

ebos/ecltransmissibility.hh
Face centers are computed using the cell corners. With this
implementation the face center seen from a cell may be different from the
face center seen from its neighbor.
Face normals with area lengths are calculated using the face corners
directly not using a triangulation point in the center of the face.
This gives transmissibility almost equal to eclipse.
Depends on OPM/opm-grid#261
=> Start using face geometry computed the Ecl way

ebos/eclcpgridmanager.hh
This only makes these transmissibilities available for parallel computations. The reason is that in the  sequential case, they do not need to be computed during grid creation and they are are also accessible via the problem object.
=> EclCpGridManager: export the transmissibilities of the sequential grid

ebos/eclproblem.hh
This fixes a problem with collecttoiorank which needs to be investigated
separately. The corresponding PR is #143 which does not seem to work yet.
=> When EnableEclOutput is false the EclWriter should not be created.

ewoms/models/blackoil/blackoilmodel.hh
This adds the missing function required by OPM/opm-simulators#1087
=> Added function to set SOMAX (for restarting)

ebos/eclbasegridmanager.hh
See: https://github.com/OPM/opm-simulators/issues/1099
=> Policy change: warn when missing well/group.

debian/rules, redhat/ewoms.spec
Backports from 2017.04 release branch.
=> disable native tuning in packaging

ebos/eclequilinitializer.hh
Downstream of https://github.com/OPM/opm-core/pull/1160
=> adjust for changed ParameterGroup namespacing

ebos/eclfluxmodule.hh, ewoms/models/blackoil/blackoilindices.hh
this PR contains patches for minor issues which i've stumbled over during hacking on the blackoil solvent extension. all except the last one are quite definitely harmless.
=> Ecl mobility shortcut fix

ewoms/io/vtkblackoilsolventmodule.hh, ewoms/models/blackoil/blackoilsolventmodules.hh
Tested together with solvent branch in opm-simulator for flow_ebos
=> Fixes to make the solvent module compile and run

ebos/ecltransmissibility.hh
Make the TRAN[X,Y] like flow_legacy and a bit more like Eclipse. 
With this PR TRAN[XYZ] matches whats computed in geoProps within acceptable values on Norne.
=> Use volume weighted arithmetic average of NTG for cells merged by minpv.

jenkins/build.sh
=> Add opm-simulators to jenkins downstream list

ebos/ecltransmissibility.hh
Use the unmodified ntg values to get the "correct" values when more than 2 cells are merged together using minPv. This makes the code equivalent with the code in Geoprops.
=> Fix minpvProps calculations

ebos/eclproblem.hh, ewoms/models/blackoil/blackoilsolventmodules.hh
- initialization only via Ecl Deck
- adds modification of relperms and cap-pressures for miscible runs
- adds TL mixing model for effective viscosity and density calculations
Tested on SPE1CASE2_SOLVENT_MISC_TL, SPE9_CP_CO2_MISC_TL, SPE5CASE1-3
and SPE3CASE1_SOLVENT_MISC
Issues:
- some discrepancy of the results for the SPE3 case compared to
flow_solvent.
- some extra convergence issues on the SPE5s and SPE9.
Issues most probably related to the well handling.
=> Add support for miscible solvent runs

CMakeLists.txt
=> fix build of ebos

ebos/eclproblem.hh
this is a copy-and-pasto that was introduced with #189.
=> ebos: do not mistake the pressure for the gas saturation anymore

ebos/collecttoiorank.hh, ebos/eclalugridmanager.hh, ebos/eclpeacemanwell.hh, ebos/eclpolyhedralgridmanager.hh, ebos/eclproblem.hh, ebos/ecltransmissibility.hh, ewoms/common/simulator.hh, ewoms/common/start.hh, ewoms/disc/common/fvbaselinearizer.hh, ewoms/io/restart.hh, ewoms/io/vtkmultiwriter.hh, ewoms/linear/bicgstabsolver.hh, ewoms/linear/combinedcriterion.hh, ewoms/linear/overlappingscalarproduct.hh, ewoms/models/blackoil/blackoilboundaryratevector.hh, ewoms/models/blackoil/blackoilprimaryvariables.hh, ewoms/nonlinear/newtonmethod.hh
This PR provides some minor fixes to make the code compile with the current DUNE release.
=> [cleanup] make module compile with DUNE 2.5

ewoms/disc/common/fvbasediscretization.hh
if the intensive quantities cache was disabled, this caused segmentation faults when an exception was thrown during the simulation.
=> fix up the intensive quantities caching

ewoms/models/blackoil/blackoilprimaryvariables.hh
set the gas saturation to zero and water saturation to 1.0 for water only case.
=> Avoid negative oil saturations for water only case

debian/control
after reorganizations in the build system, this reared its head.
=> add trilinos to debian packaging

ebos/eclbasegridmanager.hh, ebos/eclcpgridmanager.hh, ebos/eclproblem.hh, ebos/eclsummarywriter.hh, ebos/eclwellmanager.hh, ebos/ertwrappers.hh
Followup to: https://github.com/OPM/opm-parser/pull/1138
=> Schedule: explicitly instantiated

ewoms/models/blackoil/blackoilpolymermodules.hh, ewoms/models/blackoil/blackoilprimaryvariables.hh
This fixes two minor issues when Scalar is not double.
=> [bugfix] make code compile when Scalar != double.

ebos/eclequilinitializer.hh, ebos/eclproblem.hh
- Let ebos handle the swatinit scaling
- Keep the initial solution a bit longer so flow can output it. 
- Stop using the equilGrid in the init code. 
(The equilGrid can most probably be removed now. But not in this PR.) 
Note. Merge together with associated PR in opm-simulators.
=> Prepare for using the initial solution from ebos directly 

ewoms/io/vtkblackoilmodule.hh
this was forgotten in the last PR.
=> do not include "saturated" fluid properties in the VTK output anymore

ewoms/models/blackoil/blackoilindices.hh, ewoms/models/blackoil/blackoiltwophaseindices.hh
The inverse map may also be useful.
=> Add activeToCanonicalComponentIndex map

ebos/eclequilinitializer.hh, ebos/eclproblem.hh
Some follow up based on OPM/opm-material#268
=> Start using the BlackoilFluidState

CMakeLists.txt, ewoms-prereqs.cmake
https://github.com/OPM/opm-common/pull/304
=> changed: put prereqs in module itself

CMakeLists_files.cmake, ebos/equil/equilibrationhelpers.hh, ebos/equil/initstateequil.hh, tests/data/equil_pbvd_and_pdvd.DATA, tests/test_equil.cc
Depends on OPM/opm-parser#1182
=> Add support for PBDV and PDDV in initstateequil.hh

ebos/ecloutputblackoilmodule.hh, ebos/eclproblem.hh, ewoms/io/vtkblackoilmodule.hh, ewoms/models/blackoil/blackoilintensivequantities.hh, ewoms/models/blackoil/blackoilmodel.hh, ewoms/models/blackoil/blackoilnewtonmethod.hh, ewoms/models/blackoil/blackoilprimaryvariables.hh, ewoms/models/blackoil/blackoilproblem.hh
this is basically a simpler alternative to #255. also, it includes moving the observed maximum of the oil saturation to the problem where it IMO belongs.
=> Implement DRSDT and DRVDT

INSTALL
=> [cleanup] mark DUNE build as experimental.

CMakeLists.txt, CMakeLists_files.cmake
See https://github.com/OPM/opm-common/pull/321
=> Some changes to facilitate building using a super project 

ewoms/common/start.hh, ewoms/disc/ecfv/ecfvstencil.hh
Downstream of https://github.com/OPM/opm-common/pull/326
=> Relocate files in common

ebos/collecttoiorank.hh, ebos/eclalugridvanguard.hh, ebos/eclcpgridvanguard.hh, ebos/eclpolyhedralgridvanguard.hh, ebos/ecltransmissibility.hh, ebos/equil/initstateequil.hh, tests/test_ecl_output.cpp, tests/test_equil.cc
=> Adapt to moved opm-grid headers.

ebos/eclproblem.hh
Get default ecl output directory from IOConfig.
=> Fix default output directory

ebos/ecloutputblackoilmodule.hh, ebos/eclproblem.hh, ebos/eclwriter.hh, ewoms/models/blackoil/blackoilprimaryvariables.hh
=> Fix restart norne

debian/control, dune.module, ebos/ecloutputblackoilmodule.hh, ebos/eclwriter.hh, ewoms-prereqs.cmake, ewoms/models/blackoil/blackoilpolymermodules.hh, ewoms/models/blackoil/blackoilsolventmodules.hh, jenkins/build.sh, redhat/ewoms.spec
Downstream of https://github.com/OPM/opm-common/pull/341
=> adjustments for eclipse support in opm-common

ewoms/parallel/tasklets.hh
if `barrierCondition_.notify_all()` happened while another thread was preparing to call `barrierCondition_.wait()`, the preparing thread would miss the notification and `barrierCondition_.wait()` would lock up. after this patch, this should not happen anymore because the whole wait() method of the barrier tasklet is operated with the barrier mutex locked. This has the added benefit of making the code a bit simpler.
this race only occured if condition variables do not check the predicate before waiting. My references are not very explicit about this.
=> possibly fix a race condition in the tasklet mechanism

CMakeLists.txt, ewoms/parallel/tasklets.hh, tests/test_tasklets.cc
this addresses some issues with undefined unlocking behavior in tasklets that somehow only seem to appear with MacOS.
=> Fix undefined mutex unlocking behaviour, add unit test for tasklets

ebos/eclproblem.hh, ebos/eclthresholdpressure.hh, ebos/eclwriter.hh
See: https://github.com/OPM/opm-common/pull/391
=> Use RestartValue when calling Ecl writeTimeStep

ebos/eclproblem.hh, ebos/eclthresholdpressure.hh, ebos/eclwriter.hh
=> Load thpres from restart file

ebos/eclbasevanguard.hh
... instead of just the full file name of the deck. this mirrors flow's behavior.
=> ebos: allow to specify the ECL case name

ebos/eclwellmanager.hh
=> Rename ConnectionSet -> WellConnections

ebos/eclalugridvanguard.hh, ebos/eclbasevanguard.hh, ebos/eclcpgridvanguard.hh, ebos/ecloutputblackoilmodule.hh, ebos/eclpolyhedralgridvanguard.hh, ebos/eclwellmanager.hh, tests/test_ecl_output.cc
This is a pure rename PR to make the connection vs completion naming consistent.
=> rename completion to connection

ewoms/models/ncp/ncpmodel.hh
some array must be resized if the grid changes...
=> ncp model: make it work in conjunction with grid adaptivity

ewoms/disc/common/fvbasediscretization.hh
this makes it easier to inspect the convergence behavior with paraview. Since `flow` currently does not use this code, it is unaffected.
=> newton convergence writer: provide a normalized version of the relative error

ebos/equil/equilibrationhelpers.hh, ewoms/models/blackoil/blackoilmodel.hh, ewoms/models/immiscible/immisciblemodel.hh, ewoms/models/richards/richardsmodel.hh, tests/problems/co2injectionproblem.hh, tests/problems/cuvetteproblem.hh, tests/problems/diffusionproblem.hh, tests/problems/infiltrationproblem.hh, tests/problems/obstacleproblem.hh, tests/problems/outflowproblem.hh, tests/problems/reservoirproblem.hh, tests/problems/waterairproblem.hh
this is required in conjunction with OPM/opm-material#304.
=> adapt to the fluid system naming convention change in opm-material

ebos/collecttoiorank.hh
I see no compilation problems with this, let's see if Jenkins agrees.
=> Restore const-ness accidentally lost.

ebos/eclbasevanguard.hh
the previous error message was a bit confusing.
This should fix one of @atgeirr's itches!?
=> ebos: complain more explicitly about the input deck being unspecified

ewoms/models/blackoil/blackoilnewtonmethod.hh, ewoms/models/blackoil/blackoilsolventmodules.hh
Add some more tricks from flow used in the newton update to make the solvent simulation fly again
Fix fallout for 2p cases 
I would like to test this a bit more before merging.
=> Fix issues in the newton update

CMakeLists.txt
Try to "fix" test failures here: https://github.com/OPM/opm-common/pull/464
=> Add --threads-per-process=1 to test

ebos/eclwriter.hh
Followup to: https://github.com/OPM/opm-common/pull/479
=> Change string used for THPRES in restartfile

ebos/ecloutputblackoilmodule.hh
=> Store capillary pressure

ebos/eclwellmanager.hh
Downstream of: https://github.com/OPM/opm-common/pull/464
=> Wellconnection updates

ebos/eclbasevanguard.hh, ebos/eclproblem.hh
See: https://github.com/OPM/opm-common/pull/493
This is a policy decision - please voice your opinion.
=> Add --opm-rst-file parameter

ewoms/common/start.hh
this should help prevent the terminal from being deranged after the simulator has been aborted by user intervention in more cases.
Also, we now reset the TTY if an exception was received on the top-level.
=> reset the TTY after the simulator was interrupted more reliably

ebos/eclproblem.hh
this fixes #392. thanks to @bska for catching this.
=> EclProblem: only create the eclWriter_ object once

dune.module
and the winner is *drumroll*: "Lance".
=> pick a new codename for the 2019.04 version of eWoms

ebos/eclbasevanguard.hh
With this: https://github.com/OPM/opm-common/pull/515 we can now add the commandline option:
```
flow --ignore-keywords=KEY1:KEY2
```
to ignore occurences of the keywords `KEY1` and `KEY2` in the deck, with invoking the full `PARSE_UNKNOWN_KEYWORD` error control.
=> Add commandline parameter --ignore-keywords=

ebos/ecltransmissibility.hh
Depends on OPM/opm-common#462
This is an alternative to OPM/opm-common#522 and friends. 
Tested on simple case.
=> Support modifying trans from deck

ebos/eclproblem.hh, ebos/ecltransmissibility.hh
=> add support for minpvv

ebos/eclbaseaquifermodel.hh, ebos/ecloutputblackoilmodule.hh, ebos/equil/equilibrationhelpers.hh, ewoms/disc/common/fvbaselinearizer.hh, ewoms/linear/blacklist.hh, ewoms/models/common/diffusionmodule.hh, ewoms/parallel/threadedentityiterator.hh, tests/problems/lensproblem.hh
This PR deals with some minor code maintainance issues. it should not have any impact on the produced binaries.
=> Minor cleanups

ebos/eclbaseaquifermodel.hh, ebos/eclproblem.hh
nothing is perfect on first try...
=> extend the aquifer model so that it can initialize itself

ewoms/common/parametersystem.hh
the macro is called `EWOMS_PARAM_IS_SET()` and is currently unused. Nevertheless it might be useful to have in some situations, but use with great care!
=> parameter system: make it possible to determine if a parameter has been set at runtime

ebos/eclbasevanguard.hh, ebos/eclproblem.hh
=> Add support for region DR[SV]DTR

ewoms/models/ncp/ncpnewtonmethod.hh
this guards against encountering negative fugacities and too small fugacity coefficients during the Newton-Raphson update. it is obviously possible to game these mechanisms, but for the vast majority of physical fluid systems they should work fine...
=> ncp: improve the crash barriers for the fugacity update during Newton method

ebos/ecltransmissibility.hh
=> Fixed potential derefernce of end operator when applying EDITNNC.

ewoms/linear/overlappingblockvector.hh, ewoms/linear/parallelbasebackend.hh, ewoms/linear/superlubackend.hh, ewoms/nonlinear/newtonmethod.hh
I'm not 100% sure about the performance implications, though I'm reasonably confident that the results are still correct. test well before merge!
=> linear solver backends: merge prepareMatrix() and prepareRhs() to prepare

ebos/ecloutputblackoilmodule.hh, ebos/eclwriter.hh
this PR does the same as #413 but in a more ewomsy way.
=> ebos: only write out temperature in thermal runs

ebos/ecltransmissibility.hh
=> Add support for the Multz option ALL in PINCH

ebos/eclbasevanguard.hh
Downstream of: https://github.com/OPM/opm-common/pull/602
=> Add ErrorGuard argument when parsing

ebos/eclproblem.hh
since OPM/opm-material#310 has been merged, data for deactivated phases is not stored anymore and can thus no longer be accessed/set.
this fixes OPM/opm-simulators#1686
=> ebos: fix explicit initialization for twophase cases

ebos/eclproblem.hh
lastRs_, lastRv_, maxDRs_, maxDRv_
to get better restart.
Trying to fix the restart issue related to SPE1CASE1 reported in https://github.com/OPM/opm-simulators/issues/1699
This PR is done with @hnil and @bska .
=> updating more quantities when restart

ebos/eclpeacemanwell.hh, ebos/eclwellmanager.hh
In this PR only trivial data is added.
=> Add trivial connection output to silence the output code

ebos/ecloutputblackoilmodule.hh
Add unit conversion of FIP output in case of LAB unit system.
=> convert FIP values to LAB scale

ebos/eclproblem.hh
it helps to recover some RESTART running based on single precision format.
Because saturation values are used to determine saturated/unsaturated region distribution, with this patch, we are more likely to get more continuous region distribution, numerically, more continuous primary variable distribution. 
Physically, it does not matter, while numerically, the linear system is easier to solve.
=> each phase needs to be above certain value to be treated to be present

ebos/alucartesianindexmapper.hh, ebos/eclfluxmodule.hh, ebos/ecloutputblackoilmodule.hh, ebos/eclpeacemanwell.hh, ebos/eclproblem.hh, ebos/ecltracermodel.hh, ebos/ecltransmissibility.hh, ebos/eclwriter.hh, ebos/femcpgridcompat.hh, ebos/tracervdtable.hh, ewoms/disc/common/fvbaseelementcontext.hh, ewoms/models/blackoil/blackoilnewtonmethod.hh, ewoms/models/blackoil/blackoilpolymermodules.hh, ewoms/models/blackoil/blackoilprimaryvariables.hh, ewoms/models/blackoil/blackoilratevector.hh, ewoms/models/blackoil/blackoilsolventmodules.hh
This PR fixes multiple coding style issues that have accumulated in the code base with the purpose to make it more consistent. I've refrained from renaming anything which is used by downstream modules and thus intent self-merge it early next week.
=> Fix coding style

ebos/eclcpgridvanguard.hh, ebos/ecltransmissibility.hh
With this, arbitrary NNCs should work. No testing yet, so still work in progress. Requires OPM/opm-grid#355.
=> Use NNC support from CpGrid.

ebos/eclproblem.hh
the purpose of this was a hack to be able to manipulate the Jacobian to include the wells matrix directly from exterior code. Since `flow` has been converted to the eWoms wells API, this is not required anymore.
=> ebos: remove the DisableWells property

ebos/eclproblem.hh
As far as I can see, this was always set to `false` anyway.
=> ebos: remove the code to calculate a mass conservative initial condtion if the specified condition is inconsistent

ebos/eclproblem.hh, ewoms/disc/common/fvbaseproblem.hh
this only implements the parameters that are currently supported by `flow`.
large parts of this patch are due to a collaboration with @totto82. Thanks!
=> ebos: implement partial support for the TUNING keyword

ewoms/models/common/multiphasebasemodel.hh, ewoms/nonlinear/newtonmethod.hh, tests/co2injection_flash_ecfv.cc, tests/co2injection_flash_ni_ecfv.cc, tests/co2injection_flash_ni_vcfv.cc, tests/co2injection_flash_vcfv.cc, tests/problems/reservoirproblem.hh
As a consquence, the property which sets this tolerance is renamed from NewtonRawTolerance to NewtonTolerance.
=> Newton: Do not fiddle around with the user specified tolerance anymore

ewoms/common/start.hh
some MPI libraries (i.e., openMPI 3.1.1.0, the one installed on my system) have the annoying habit of gobbling up about 1 second for `MPI_Init()`. While this is not a big deal when running a simulation, it is really annoying for tab completion. Thus, deal with the parameters before calling `MPI_Init()` so that the help message can be printed instantaneously.
Note that this assumes that `mpirun` does not mess around with the command line parameters. This seems to be the case for at least openMPI and MPICH, but -- as far as I know -- this behavior is not guaranteed by the MPI standard.
A better approach would be to detect if the simulator is started via `mpirun` and only defer the call to `MPI_Init()` if this is not the case. Unfortunately, I am not aware of any way to do this generically. …
=> start(): call MPI_Init() after dealing with the command line parameters

CMakeLists.txt
=> remove bash completion generation

ewoms/common/simulator.hh
Exit the simulation, if load balancing results in a process with zero cells.
depends on a branch with the same name in opm-grid
fixes https://github.com/OPM/opm-simulators/issues/1726 when combined with OPM/opm-grid#361
=> catch when a process throws

ewoms/common/simulator.hh
this only affects binaries which do use set `verbose_` flag, i.e., not `flow`.
=> simulator: print the error messages of the thrown exceptions in case something goes wrong during init

ewoms/models/blackoil/blackoilpolymermodules.hh
fixing error reported in https://github.com/OPM/ewoms/issues/496 by @bska
=> fixing a small mistake in getSkprwatTable

ewoms/linear/parallelbasebackend.hh, ewoms/models/blackoil/blackoilsolventmodules.hh
Would be nice if this would get into the release.
=> Removes unsused function parameter warning

ewoms/common/parametersystem.hh
this are "drive by" fixes while I was working on something else last week;
- make code which uses the `EWOMS_PARAM_IS_SET` macro compile
- make it possible to reset the parameter machinery. this is an  advanced function which might eat children! only use it if you know  what you're doing!
=> parameter system: some fixes and improvements

ewoms/models/blackoil/blackoilpolymermodules.hh
to obtain more well defined behavoir
=> using createConstantOne instead of createBlank

ewoms/common/parametersystem.hh, ewoms/models/blackoil/blackoilenergymodules.hh
Quells some warnings with -Wshadow and -Wextra.
=> Some janitoring

ewoms/linear/blacklist.hh, ewoms/linear/domesticoverlapfrombcrsmatrix.hh, ewoms/linear/foreignoverlapfrombcrsmatrix.hh, ewoms/linear/overlappingbcrsmatrix.hh, ewoms/parallel/mpibuffer.hh
ref https://ci.opm-project.org/job/ewoms/12/gcc/
=> changed: suppress unused variable warnings without mpi

debian/rules, redhat/opm-models.spec
Fallout after opm-models rename
=> Fix packaging fallout

opm/models/blackoil/blackoilpolymermodules.hh
Should fix OPM/opm-simulators#2032
=> fix bug in PLYROCK

opm/models/blackoil/blackoilenergymodules.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilonephaseindices.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/blackoil/blackoilratevector.hh, opm/models/blackoil/blackoiltwophaseindices.hh, opm/models/discretization/common/fvbaselocalresidual.hh, opm/models/utils/simulator.hh
This is a revised version of #510. Basically it is what I would have requested if reviewing it.
=> Enable onephase revised

CMakeLists_files.cmake
Backport of PR #556 to release
=> fixed: install blackoilonephaseindices.hh

debian/control, jenkins/build.sh, redhat/opm-models.spec
Downstream-ish of https://github.com/OPM/opm-common/pull/1107
=> remove libecl dependency

README
Change to new name of module in README file.
=> [cleanup] eWoms --> opm-models

opm/models/discretefracture/discretefractureextensivequantities.hh, opm/models/discretefracture/discretefractureintensivequantities.hh, opm/models/discretefracture/discretefracturelocalresidual.hh, opm/models/discretefracture/discretefracturemodel.hh, opm/models/discretefracture/discretefractureprimaryvariables.hh, opm/models/discretefracture/discretefractureproblem.hh, opm/models/discretefracture/discretefractureproperties.hh, opm/simulators/linalg/superlubackend.hh, tests/finger_immiscible_vcfv.cc, tests/problems/fractureproblem.hh
=> Fixed missing conversion ewoms->opm-models in header includes,

CMakeLists_files.cmake, opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilindices.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoillocalresidual.hh, opm/models/blackoil/blackoilmodel.hh, opm/models/blackoil/blackoilnewtonmethod.hh, opm/models/blackoil/blackoilonephaseindices.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/blackoil/blackoilproperties.hh, opm/models/blackoil/blackoilratevector.hh, opm/models/blackoil/blackoilsaltwatermodules.hh, opm/models/blackoil/blackoiltwophaseindices.hh
=> Trinemykk smartwater

dune.module, opm/models/blackoil/blackoilbrinemodules.hh, opm/models/discretization/common/fvbasediscretization.hh, opm/models/discretization/common/fvbaselinearizer.hh, opm/models/discretization/common/fvbaseproblem.hh, opm/models/discretization/ecfv/ecfvstencil.hh, opm/models/discretization/vcfv/vcfvstencil.hh, opm/models/io/dgfvanguard.hh, opm/models/io/vtkmultiwriter.hh, opm/models/nonlinear/newtonmethod.hh, opm/models/utils/pffgridvector.hh, opm/models/utils/start.hh, opm/simulators/linalg/overlappingoperator.hh, opm/simulators/linalg/overlappingpreconditioner.hh, opm/simulators/linalg/overlappingscalarproduct.hh
=> bump required dune version to 2.6

opm-models-prereqs.cmake
Downstream of https://github.com/OPM/opm-common/pull/1456
=> remove usage of CXX11Features module

opm/models/blackoil/blackoilbrinemodules.hh
Downstream of https://github.com/OPM/opm-material/pull/392
=> add mpi serialization for BlackoilBrineModule

opm/models/blackoil/blackoilsolventmodules.hh
required for the SolventPvt setup
Downstream of https://github.com/OPM/opm-material/pull/411
=> changed: pass the Schedule through the SolventModule::initFromDeck method

opm/models/blackoil/blackoilsolventmodules.hh
Downstream of https://github.com/OPM/opm-common/pull/1529
=> use TLMIXPAR from state

opm/models/blackoil/blackoilsolventmodules.hh
Thus we remove the need for serialization.
=> Remove deck usage from BlackoilSolventModule

CMakeLists.txt
Had problems with this utility at one location - should not really be important; so wrapped in a conditinal.
=> Wrap the art2dgf utility in if (BUILD_EXAMPLES) ...  endif()

opm/models/blackoil/blackoilbrinemodules.hh
As a consequence we do not have to serialize it any longer.
=> Get rid of deck usage in BlackoilBrineModule

opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilonephaseindices.hh
and anonymize unused parameters
=> mark conditionally used parameters as maybe_unused

opm/models/io/vtkblackoilmodule.hh
This includes such things as saturation pressures, rs, rv etc.
This is necessary in addition to #613, for water-oil cases.
=> Make gas-oil related outputs conditional.

opm/models/utils/start.hh
That is the documented convention and needed to be able to mark these runs as successful.
=> Use negative status to indicate --help, --print-properties, --print-parameters

opm/models/blackoil/blackoilsolventmodules.hh
Downstream of: https://github.com/OPM/opm-common/pull/1875
=> Use non table TLMIXPAR implementation

opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilenergymodules.hh, opm/models/blackoil/blackoilfoammodules.hh, opm/models/blackoil/blackoilmodel.hh, opm/models/blackoil/blackoilpolymermodules.hh, opm/models/common/diffusionmodule.hh, opm/models/common/energymodule.hh, opm/models/common/multiphasebaseproblem.hh, opm/models/discretefracture/discretefractureproblem.hh, opm/models/discretization/common/fvbaseelementcontext.hh, opm/models/discretization/common/fvbaselocalresidual.hh, opm/models/discretization/common/fvbaseproblem.hh, opm/models/io/baseoutputmodule.hh, opm/models/io/vtktensorfunction.hh, opm/models/parallel/threadmanager.hh, opm/models/utils/parametersystem.hh, opm/simulators/linalg/nullborderlistmanager.hh
See: https://github.com/OPM/opm-material/pull/428
=> Remove unused #include of Exceptions

CMakeLists_files.cmake, opm/models/blackoil/blackoilextbomodules.hh, opm/models/blackoil/blackoilindices.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoillocalresidual.hh, opm/models/blackoil/blackoilmodel.hh, opm/models/blackoil/blackoilnewtonmethod.hh, opm/models/blackoil/blackoilonephaseindices.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/blackoil/blackoilproperties.hh, opm/models/blackoil/blackoiltwophaseindices.hh
A first version, depending on corresponding pr for opm-simulators (extboSimulators) and opm-common (kwPVTEXTBO).
=> Alternative solvent extension for the black oil model.

opm/models/discretization/common/fvbaseboundarycontext.hh, opm/models/discretization/common/fvbaselocalresidual.hh
Make sure that the iterator continues beyond the first boundary
=> fix incrementer in boundarycontext

opm/models/blackoil/blackoilpolymermodules.hh
Upstream changes will make this change necessary, however this can be merged separately as such.
=> blackoilpolymermodules: include OpmLog.h

opm/models/blackoil/blackoilnewtonmethod.hh
We may want to change the default values, but for now they seem good enough.
=> Restrict the temperature update using provided parameters

tests/problems/reservoirproblem.hh
Downstream of https://github.com/OPM/opm-material/pull/459
=> adjust to enum changes in upstream

opm/models/common/multiphasebasemodel.hh, opm/models/discretization/common/baseauxiliarymodule.hh, opm/models/discretization/common/fvbaseelementcontext.hh, opm/models/discretization/ecfv/ecfvstencil.hh, opm/models/discretization/vcfv/vcfvstencil.hh, opm/models/immiscible/immisciblemodel.hh, opm/models/ncp/ncpmodel.hh, opm/models/parallel/mpibuffer.hh, opm/models/pvs/pvsmodel.hh, opm/models/richards/richardsmodel.hh
=> fixed: do not assert conditions guaranteed by unsigned

redhat/opm-models.spec
- use system level boost now that RHEL6 is dead
=> fix redhat packaging

opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilmodel.hh, opm/models/blackoil/blackoilnewtonmethod.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/blackoil/blackoiltwophaseindices.hh
Fixes to allow for gas-water system
=> adjustments needed for gas-water system

opm/models/blackoil/blackoilextbomodules.hh
To avoid assertions, ref https://github.com/OPM/opm-common/pull/2594
=> extbomodule: enable extrapolation for function evaluations

opm/models/utils/simulator.hh
adding the  communicator as input for the simulator calls
=> Communicators2

opm/models/io/vtkmultiwriter.hh
Downstream of https://github.com/OPM/opm-common/pull/2802
=> use std::filesystem directly

opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilmodel.hh, opm/models/blackoil/blackoilproperties.hh
Extension of PR https://github.com/OPM/opm-material/pull/429
=> update parameters BlackoilFluidSystem

opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilextbomodules.hh, opm/models/blackoil/blackoilfoammodules.hh, opm/models/blackoil/blackoilmicpmodules.hh, opm/models/blackoil/blackoilpolymermodules.hh, opm/models/blackoil/blackoilsolventmodules.hh
Downstream of: https://github.com/OPM/opm-common/pull/2903
=> Downstream of filesystem reorganisation in opm-common

opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilnewtonmethod.hh, opm/models/blackoil/blackoilprimaryvariables.hh
Main contents of this PR is 
1. The extension of the brine module to deal with salt precipitation/dissolution. 
2. Allowing primary variable switching between salt concentration and solid( precipitated) salt
This PR depends on https://github.com/OPM/opm-material/pull/490
=> Enable salt precipitation/dissolution

CMakeLists.txt, CMakeLists_files.cmake, opm/models/common/transfluxmodule.hh, tests/lens_immiscible_ecfv_ad_trans.cc, tests/problems/lensproblem.hh
Compute flux based on transmissibilites. The permeability is assumed to be diagonal and aligned with the local cell.
=> Add transflux module and a test that uses it

opm/models/discretization/common/fvbaseadlocallinearizer.hh
I doubt this will yield any relevant gains but nontheless it's small optimizations.
=> Small micro optimizations

opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilnewtonmethod.hh, opm/models/blackoil/blackoilprimaryvariables.hh
This PR is part of a set of PRs to allow for water evaporation into gas in combination with oil vaporization.
This PR adds new primary variable combination and switches relevant for combined vaporization of water and oil into the gas phase.
=> adding primary variable combination/switching 

opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilfoammodules.hh, opm/models/blackoil/blackoilsolventmodules.hh
(Sort of) downstream of https://github.com/OPM/opm-common/pull/3083
=> remove unnecessary includes

opm/models/discretization/vcfv/p1fegradientcalculator.hh, tests/problems/fractureproblem.hh
Needed for configurations that don't have Dune-localfunctions or which **do** have ALUGrid.
=> Fix Build After "Unused.hpp" Removal

opm/models/blackoil/blackoilboundaryratevector.hh, opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilenergymodules.hh, opm/models/blackoil/blackoilextbomodules.hh, opm/models/blackoil/blackoilfoammodules.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilmodel.hh, opm/models/blackoil/blackoilpolymermodules.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/blackoil/blackoilratevector.hh, opm/models/blackoil/blackoilsolventmodules.hh
Use if constexpr to avoid building code when appropriate.
=> Modernization in blackoil model

opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/blackoil/blackoilsolventmodules.hh
Downstream of https://github.com/OPM/opm-material/pull/529
=> changed: consistently use std::array

opm/models/blackoil/blackoilmodel.hh
Use the same weights here as in the getConvergence methods in the Flow part of the code. 
These weights are currently only used by the drift compensation code. 
We could consider using these weights instead of computing them over an over again in the getConvergence method. Initial testing indicates that this does not give any significant differences. That could give a decent speed-up since we then no-longer need to integrate over the elements jf recent work on speeding up the assembly.
=> Set eq weights externally in the blackoil model

opm/models/blackoil/blackoilprimaryvariables.hh
This PR fixes the negative water saturations observed in  https://github.com/OPM/opm-simulators/pull/4002.
=> fix for gaswater system with water evaporation

CMakeLists_files.cmake, opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilbrineparams.hh
limit the amount of static variable initialization statements.
=> BlackOilBrineModules: put parameters in separate struct

CMakeLists_files.cmake, opm/models/blackoil/blackoilpolymermodules.hh, opm/models/blackoil/blackoilpolymerparams.hh
limits the amount of static variable declarations
=> blackoilpolymermodules: put parameters in separate class

CMakeLists_files.cmake, opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilextbomodules.hh, opm/models/blackoil/blackoilextboparams.hh
limits the amount of static variable declarations
=> blackoilextbomodules: put parameters in separate class

CMakeLists_files.cmake, opm/models/blackoil/blackoilfoammodules.hh, opm/models/blackoil/blackoilfoamparams.hh
limits the amount of static variable declarations
=> blackoilfoammodules: put parameters in separate class

opm/models/blackoil/blackoilintensivequantities.hh
This fix solve a convergence issue when water disappears due to evaporation
=> bug fix: missing setRs added

opm/models/blackoil/blackoilmodel.hh, opm/models/common/multiphasebaseproblem.hh, opm/models/discretization/common/fvbasediscretization.hh, opm/models/discretization/common/fvbaselinearizer.hh, opm/models/discretization/common/tpfalinearizer.hh, opm/models/pvs/pvsmodel.hh, opm/models/utils/pffgridvector.hh, opm/simulators/linalg/elementborderlistfromgrid.hh, tests/problems/fingerproblem.hh, tests/problems/richardslensproblem.hh
=> Use elements range generator

opm/models/discretization/common/fvbaselinearizer.hh, opm/models/discretization/common/tpfalinearizer.hh
Implement for the TpfaLinearizer to update transmissibilities.
=> Add interface for updating stored parameters in linearizers.

opm/models/discretization/common/tpfalinearizer.hh
Depends on OPM/opm-common#3185
=> implement dirichlet boundary conditions

opm/models/discretization/vcfv/vcfvstencil.hh, tests/test_quadrature.cc
Related to https://github.com/OPM/opm-common/pull/3219
=> Fix test_quadrature with dune-alugrid

opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoilbrineparams.hh
Depends on https://github.com/OPM/opm-common/pull/2981
=> add Salt Density

dune.module, jenkins/build.sh, opm-models-prereqs.cmake
remove opm-material from upstreams / dependencies
Downstream of https://github.com/OPM/opm-common/pull/3234
=> adjust jenkins script and buildsystem

tests/problems/reservoirproblem.hh
Downstream of https://github.com/OPM/opm-common/pull/3252
=> Adjust to upstream enum entry changes

art2dgf/art2dgf.cc, opm/models/blackoil/blackoilnewtonmethod.hh, opm/models/blackoil/blackoilsolventmodules.hh, opm/models/common/darcyfluxmodule.hh, opm/models/common/forchheimerfluxmodule.hh, opm/models/discretefracture/discretefracturemodel.hh, opm/models/discretization/common/fvbasediscretization.hh, opm/models/discretization/common/fvbaselinearizer.hh, opm/models/discretization/common/fvbaseprimaryvariables.hh, opm/models/discretization/common/tpfalinearizer.hh, opm/models/discretization/vcfv/vcfvstencil.hh, opm/models/io/vtkscalarfunction.hh, opm/models/io/vtkvectorfunction.hh, opm/models/ncp/ncpmodel.hh, opm/models/ncp/ncpnewtonmethod.hh, opm/models/nonlinear/newtonmethod.hh, opm/models/pvs/pvsmodel.hh, opm/models/pvs/pvsprimaryvariables.hh, opm/simulators/linalg/bicgstabsolver.hh, opm/simulators/linalg/overlappingpreconditioner.hh, opm/simulators/linalg/parallelbasebackend.hh
Downstream of https://github.com/OPM/opm-common/pull/3259
=> use exception classes from opm-common

opm/models/ncp/ncpmodel.hh, opm/models/pvs/pvsprimaryvariables.hh, opm/simulators/linalg/bicgstabsolver.hh
=> remove namespace qualifiers from symbols in Opm namespace

tests/problems/co2injectionproblem.hh
Downstream of https://github.com/OPM/opm-common/pull/3285
=> adjust to upstream CO2Table encapsulation

opm/models/blackoil/blackoilsolventmodules.hh
Only modify density (i.e) the effective gravity contribution and not the volumes itself.
=> Fix Todd-Longstaff model for density. 

opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/discretization/common/fvbaselinearizer.hh, opm/models/discretization/common/tpfalinearizer.hh
See https://github.com/OPM/opm-simulators/pull/4275 for rationale.
=> FLOWS and FLORES support

opm/models/blackoil/blackoilprimaryvariables.hh
=> BlackoilPrimaryVariables: add serialization support

opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/discretization/common/fvbaseproblem.hh, opm/models/utils/start.hh
- made output text nicer
This make output of runs from opm-model more in line with the rest of the code.
=> - removed not nice comments

opm/models/discretization/common/fvbasediscretization.hh
Sits on top of https://github.com/OPM/opm-models/pull/779
For restart.
=> FvBaseDiscretization: add serialization support

opm/models/utils/simulator.hh
=> Simulator: add serialization support

opm/models/discretization/common/fvbasediscretization.hh
Not tested to work yet, but at least it compiles.
=> Ensure serialization of the solution object also with dune-fem.

opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/discretization/common/tpfalinearizer.hh
Modification of #784 addressing missing header.
=> Add timing block

opm/models/blackoil/blackoilintensivequantities.hh, opm/models/discretization/common/tpfalinearizer.hh
Not required to build but was requested in review.
Downstream of https://github.com/OPM/opm-common/pull/3418
=> include TimingMacros.hpp where used

opm/models/blackoil/blackoilmodel.hh, opm/models/discretization/common/fvbaseintensivequantities.hh
- chaches to update full intensive quantities including extxrution factor without elementctx
=> - changes to be able to override methods in blacoilmodel

dune.module, opm/models/nonlinear/newtonmethod.hh, opm/models/nonlinear/nullconvergencewriter.hh, opm/models/utils/simulator.hh, opm/simulators/linalg/istlpreconditionerwrappers.hh, opm/simulators/linalg/matrixblock.hh, opm/simulators/linalg/overlappingscalarproduct.hh, opm/simulators/linalg/parallelamgbackend.hh, opm/simulators/linalg/parallelbasebackend.hh, opm/simulators/linalg/parallelistlbackend.hh, tests/problems/waterairproblem.hh
Leaving as draft, should be merged close to 23.04 release.
=> minimum dune version required is now 2.7

opm/models/blackoil/blackoilenergymodules.hh
Rock fraction is usually 1 - porosity, but if pvmult is used to modify porosity
we will apply the same multiplier to the rock fraction
i.e. pvmult*(1 - porosity) and thus interpret multpv as a volume
multiplier. This is to avoid negative rock volume for pvmult*porosity > 1
=> use rockfraction instead of 1 - porosity in energy equation

opm/models/blackoil/blackoilfoammodules.hh, opm/models/blackoil/blackoilfoamparams.hh
Depends on https://github.com/OPM/opm-common/pull/3523
=> Extend foam model with solvent or water

opm/models/parallel/threadmanager.hh
We actually do set the number of OpenMP threads based on OMP_NUM_THREADS or command line option ThreadsPerProcess for OpenMP already in opm-simulators and these settings should just be used here, too. Hence the new flag for skipping the command line parameter and use the number of threads that OpenMP has available.
Querying it here results in different behavior as for FlowMainEbos.hpp: In opm-simulators variable OMP_NUM_THREADS takes precedence over the command line parameter, but here it would only be used if the command line option was not used at all.
Companion PR in opm-simulators is coming.
=> ThreadManager: Allow querying number of threads from OpenMP in init.

opm/models/parallel/threadmanager.hh
Right brace must be outside ifdefs.
=> Fix OPENMP ifdefs.

opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/discretization/common/fvbaselinearizer.hh, opm/models/discretization/common/tpfalinearizer.hh
Depends on https://github.com/OPM/opm-common/pull/3482
=> support BC in schedule

opm/models/discretization/common/tpfalinearizer.hh
=> Janitoring: add missing include

opm/models/blackoil/blackoilproperties.hh, opm/models/io/baseoutputmodule.hh
-- added tag for mechanical solver defaulted to false
=> added enableMech

opm/models/blackoil/blackoillocalresidualtpfa.hh
=> -- added missing include

CMakeLists_files.cmake, opm/models/discretization/common/fvbasediscretization.hh, opm/models/discretization/common/fvbasediscretizationfemadapt.hh, opm/models/discretization/common/fvbaseproperties.hh, opm/models/discretization/ecfv/ecfvdiscretization.hh, opm/models/discretization/vcfv/vcfvdiscretization.hh, opm/models/io/basevanguard.hh
introduced base discretization in tagsystem to be able to change between dunefem adaptation or not
This is a rebased, fixed and improved version of #815
=> move the dynamic refinement part related to dune fem to separate class

opm/models/utils/simulator.hh
We have experienced some deadlocks lately because of programming errors. This change will not result in a clean exit for those but rather an abort by MPI because of non-matching communications.
Also we cannot forsee whether people will add more exceptions in those parts that were not protected. We better play it safe here.
=> Try to detect more exceptions during parallel simulator setup.

opm/models/blackoil/blackoilenergymodules.hh, opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/blackoil/blackoilmodel.hh, opm/models/discretization/common/tpfalinearizer.hh
-- added need functions for beeing able to use TPFA linearizer for energy simulation
=> TPFA version for energy

opm/models/blackoil/blackoildiffusionmodule.hh, opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/discretization/common/tpfalinearizer.hh
fixed tpfa for diffusion module
This replaces https://github.com/OPM/opm-models/pull/824 for convenience.
=> add tpfa diffusion

opm/models/blackoil/blackoilenergymodules.hh
=> anonymize unused parameters

opm/models/blackoil/blackoilfoamparams.hh
=> Included missing header causing compile errors with gcc-13

opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/discretization/common/tpfalinearizer.hh
=> Fix BC Free for 2p problems

opm/models/parallel/mpibuffer.hh
=> [backport] Skip manual error checking of MPI_Recv

opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/discretization/common/fvbaselinearizer.hh, opm/models/discretization/common/tpfalinearizer.hh
This PR also refactor the computation of flows and flores to a separate call.
=> Add bondary flux output 

opm/models/blackoil/blackoilnewtonmethod.hh
-- add max and min pressure.
This can ensure that one limit evaluations outside tables.
Probably one should change defaults on min temperature to 0 C.
=> added max and minpressure

opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/discretization/common/fvbasediscretization.hh, opm/models/discretization/common/fvbaseprimaryvariables.hh
…e scaling for reservoir
- the missing scaling is for RS/RV
=> Pressure scaling for reservoir

opm/models/blackoil/blackoillocalresidualtpfa.hh
This PR allows to set the no flux and constant temperature on the top (1) and bottom (2) boundaries for the SPE11B/C cases: 
```
BCPROP
1 THERMAL /
2 THERMAL /
/
```
=> Thermal BC for spe11bc

opm/models/blackoil/blackoildiffusionmodule.hh
Depends on https://github.com/OPM/opm-common/pull/3878
=> Add mass fraction diffusion coefficients

opm/models/common/directionalmobility.hh
Discovered while shuffling headers around
=> add missing include

opm/models/blackoil/blackoildiffusionmodule.hh
Is for convenience build on #868
=> Enables diffusion of water in gas phase

opm/models/discretization/common/tpfalinearizer.hh
=> adjust to output module accessor change

opm/models/utils/parametersystem.hh, opm/models/utils/start.hh
it adds no simplicity and only obfuscates
=> remove EWOMS_END_PARAM_REGISTRATION macro

opm/models/utils/parametersystem.hh
pass property struct instead of name of stringified parameter.
=> Parameters::hideParam

opm/models/utils/parametersystem.hh
- remove check_  - no way to access parameters using wrong type any more
- remove Param<TypeTag> wrapper
- replace iterator loops with range based loops
=> ParameterSystem: some cleanup

CMakeLists_files.cmake, opm/models/ncp/ncpnewtonmethod.hh, opm/models/nonlinear/newtonmethod.hh, opm/models/nonlinear/newtonmethodparameters.hh, opm/models/nonlinear/newtonmethodproperties.hh, tests/co2injection_flash_ecfv.cc, tests/co2injection_flash_ni_ecfv.cc, tests/co2injection_flash_ni_vcfv.cc, tests/co2injection_flash_vcfv.cc, tests/problems/co2injectionproblem.hh, tests/problems/co2ptflashproblem.hh, tests/problems/fingerproblem.hh, tests/problems/infiltrationproblem.hh, tests/problems/lensproblem.hh, tests/problems/reservoirproblem.hh, tests/problems/richardslensproblem.hh, tests/problems/waterairproblem.hh
=> NewtonMethod: split parameters and properties

CMakeLists.txt
And fix a test that is now activated since we build with dune-alugrid
Downstream of https://github.com/OPM/opm-common/pull/4132
=> Fix QuadMath handling

opm/models/immiscible/immisciblemodel.hh, opm/models/io/baseoutputmodule.hh, opm/models/io/vtkblackoilenergymodule.hh, opm/models/io/vtkblackoilmicpmodule.hh, opm/models/io/vtkblackoilmodule.hh, opm/models/io/vtkblackoilpolymermodule.hh, opm/models/io/vtkblackoilsolventmodule.hh, opm/models/io/vtkcompositionmodule.hh, opm/models/io/vtkdiffusionmodule.hh, opm/models/io/vtkdiscretefracturemodule.hh, opm/models/io/vtkenergymodule.hh, opm/models/io/vtkmultiphasemodule.hh, opm/models/io/vtkphasepresencemodule.hh, opm/models/io/vtkprimaryvarsmodule.hh, opm/models/io/vtkptflashmodule.hh, opm/models/io/vtktemperaturemodule.hh, tests/problems/co2ptflashproblem.hh, tests/problems/lensproblem.hh, tests/problems/outflowproblem.hh, tests/problems/powerinjectionproblem.hh
Continue splitting parameters and properties
=> Move vtk parameters to Opm::Parameters namespace

opm/models/io/baseoutputmodule.hh
=> BaseOutputModule: some cleanup

opm/models/blackoil/blackoilconvectivemixingmodule.hh
=> blackoilConvectiveMixingModule: anonymize unused parameters

opm/models/utils/parametersystem.hh, opm/models/utils/propertysystem.hh
It has now been fully replaced with the typetag free system.
=> remove typetag based parameter system

opm/models/blackoil/blackoilconvectivemixingmodule.hh
Depends on https://github.com/OPM/opm-common/pull/4161
=> support drsdtcon with pvtnum
